# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from spice_harvester_sdk.models.ai_intent_route import AIIntentRoute
from spice_harvester_sdk.models.ai_intent_type import AIIntentType
from typing import Optional, Set
from typing_extensions import Self

class AIIntentResponse(BaseModel):
    """
    AIIntentResponse
    """ # noqa: E501
    clarifying_question: Optional[StrictStr] = None
    confidence: Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]
    intent: AIIntentType
    llm: Optional[Dict[str, Any]] = None
    missing_fields: Optional[List[StrictStr]] = None
    reply: Optional[StrictStr] = None
    requires_clarification: Optional[StrictBool] = False
    route: AIIntentRoute
    __properties: ClassVar[List[str]] = ["clarifying_question", "confidence", "intent", "llm", "missing_fields", "reply", "requires_clarification", "route"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIIntentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIIntentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clarifying_question": obj.get("clarifying_question"),
            "confidence": obj.get("confidence"),
            "intent": obj.get("intent"),
            "llm": obj.get("llm"),
            "missing_fields": obj.get("missing_fields"),
            "reply": obj.get("reply"),
            "requires_clarification": obj.get("requires_clarification") if obj.get("requires_clarification") is not None else False,
            "route": obj.get("route")
        })
        return _obj


