# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from spice_harvester_sdk.models.ai_query_tool import AIQueryTool
from spice_harvester_sdk.models.dataset_list_query import DatasetListQuery
from spice_harvester_sdk.models.graph_query_request import GraphQueryRequest
from spice_harvester_sdk.models.query_input import QueryInput
from typing import Optional, Set
from typing_extensions import Self

class AIQueryPlan(BaseModel):
    """
    LLM-produced query plan.  Safety contract: - The plan is *only* a recommendation. Server validates and enforces caps. - Output must be JSON (schema-validated).
    """ # noqa: E501
    confidence: Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]
    dataset_query: Optional[DatasetListQuery] = None
    graph_query: Optional[GraphQueryRequest] = None
    interpretation: StrictStr = Field(description="Human-readable interpretation of the question")
    query: Optional[QueryInput] = None
    tool: AIQueryTool
    warnings: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["confidence", "dataset_query", "graph_query", "interpretation", "query", "tool", "warnings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIQueryPlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dataset_query
        if self.dataset_query:
            _dict['dataset_query'] = self.dataset_query.to_dict()
        # override the default output from pydantic by calling `to_dict()` of graph_query
        if self.graph_query:
            _dict['graph_query'] = self.graph_query.to_dict()
        # override the default output from pydantic by calling `to_dict()` of query
        if self.query:
            _dict['query'] = self.query.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIQueryPlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "confidence": obj.get("confidence"),
            "dataset_query": DatasetListQuery.from_dict(obj["dataset_query"]) if obj.get("dataset_query") is not None else None,
            "graph_query": GraphQueryRequest.from_dict(obj["graph_query"]) if obj.get("graph_query") is not None else None,
            "interpretation": obj.get("interpretation"),
            "query": QueryInput.from_dict(obj["query"]) if obj.get("query") is not None else None,
            "tool": obj.get("tool"),
            "warnings": obj.get("warnings")
        })
        return _obj


