# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from spice_harvester_sdk.models.graph_hop import GraphHop
from typing import Optional, Set
from typing_extensions import Self

class GraphQueryRequest(BaseModel):
    """
    Request model for multi-hop graph queries.
    """ # noqa: E501
    filters: Optional[Dict[str, Any]] = None
    hops: List[GraphHop]
    include_audit: Optional[StrictBool] = False
    include_documents: Optional[StrictBool] = True
    include_paths: Optional[StrictBool] = False
    include_provenance: Optional[StrictBool] = False
    limit: Optional[StrictInt] = 100
    max_edges: Optional[StrictInt] = 2000
    max_nodes: Optional[StrictInt] = 500
    max_paths: Optional[StrictInt] = 100
    no_cycles: Optional[StrictBool] = False
    offset: Optional[StrictInt] = 0
    path_depth_limit: Optional[StrictInt] = None
    start_class: StrictStr
    __properties: ClassVar[List[str]] = ["filters", "hops", "include_audit", "include_documents", "include_paths", "include_provenance", "limit", "max_edges", "max_nodes", "max_paths", "no_cycles", "offset", "path_depth_limit", "start_class"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphQueryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in hops (list)
        _items = []
        if self.hops:
            for _item_hops in self.hops:
                if _item_hops:
                    _items.append(_item_hops.to_dict())
            _dict['hops'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphQueryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "filters": obj.get("filters"),
            "hops": [GraphHop.from_dict(_item) for _item in obj["hops"]] if obj.get("hops") is not None else None,
            "include_audit": obj.get("include_audit") if obj.get("include_audit") is not None else False,
            "include_documents": obj.get("include_documents") if obj.get("include_documents") is not None else True,
            "include_paths": obj.get("include_paths") if obj.get("include_paths") is not None else False,
            "include_provenance": obj.get("include_provenance") if obj.get("include_provenance") is not None else False,
            "limit": obj.get("limit") if obj.get("limit") is not None else 100,
            "max_edges": obj.get("max_edges") if obj.get("max_edges") is not None else 2000,
            "max_nodes": obj.get("max_nodes") if obj.get("max_nodes") is not None else 500,
            "max_paths": obj.get("max_paths") if obj.get("max_paths") is not None else 100,
            "no_cycles": obj.get("no_cycles") if obj.get("no_cycles") is not None else False,
            "offset": obj.get("offset") if obj.get("offset") is not None else 0,
            "path_depth_limit": obj.get("path_depth_limit"),
            "start_class": obj.get("start_class")
        })
        return _obj


