# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ObjectTypeContractCreateRequestV2(BaseModel):
    """
    ObjectTypeContractCreateRequestV2
    """ # noqa: E501
    api_name: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="apiName")
    auto_generate_mapping: Optional[StrictBool] = Field(default=None, alias="autoGenerateMapping")
    backing_dataset_id: Optional[StrictStr] = Field(default=None, alias="backingDatasetId")
    backing_datasource_id: Optional[StrictStr] = Field(default=None, alias="backingDatasourceId")
    backing_datasource_version_id: Optional[StrictStr] = Field(default=None, alias="backingDatasourceVersionId")
    backing_source: Optional[Dict[str, Any]] = Field(default=None, alias="backingSource")
    backing_sources: Optional[List[Dict[str, Any]]] = Field(default=None, alias="backingSources")
    dataset_version_id: Optional[StrictStr] = Field(default=None, alias="datasetVersionId")
    mapping_spec_id: Optional[StrictStr] = Field(default=None, alias="mappingSpecId")
    mapping_spec_version: Optional[StrictInt] = Field(default=None, alias="mappingSpecVersion")
    metadata: Optional[Dict[str, Any]] = None
    pk_spec: Optional[Dict[str, Any]] = Field(default=None, alias="pkSpec")
    primary_key: Optional[StrictStr] = Field(default=None, alias="primaryKey")
    schema_hash: Optional[StrictStr] = Field(default=None, alias="schemaHash")
    status: Optional[StrictStr] = None
    title_property: Optional[StrictStr] = Field(default=None, alias="titleProperty")
    __properties: ClassVar[List[str]] = ["apiName", "autoGenerateMapping", "backingDatasetId", "backingDatasourceId", "backingDatasourceVersionId", "backingSource", "backingSources", "datasetVersionId", "mappingSpecId", "mappingSpecVersion", "metadata", "pkSpec", "primaryKey", "schemaHash", "status", "titleProperty"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObjectTypeContractCreateRequestV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObjectTypeContractCreateRequestV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiName": obj.get("apiName"),
            "autoGenerateMapping": obj.get("autoGenerateMapping"),
            "backingDatasetId": obj.get("backingDatasetId"),
            "backingDatasourceId": obj.get("backingDatasourceId"),
            "backingDatasourceVersionId": obj.get("backingDatasourceVersionId"),
            "backingSource": obj.get("backingSource"),
            "backingSources": obj.get("backingSources"),
            "datasetVersionId": obj.get("datasetVersionId"),
            "mappingSpecId": obj.get("mappingSpecId"),
            "mappingSpecVersion": obj.get("mappingSpecVersion"),
            "metadata": obj.get("metadata"),
            "pkSpec": obj.get("pkSpec"),
            "primaryKey": obj.get("primaryKey"),
            "schemaHash": obj.get("schemaHash"),
            "status": obj.get("status"),
            "titleProperty": obj.get("titleProperty")
        })
        return _obj


