# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class OntologyDeploymentRecordRequest(BaseModel):
    """
    OntologyDeploymentRecordRequest
    """ # noqa: E501
    deployed_by: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = None
    ontology_commit_id: Optional[StrictStr] = None
    snapshot_rid: Optional[StrictStr] = None
    target_branch: Optional[StrictStr] = Field(default='main', description="Deployment target branch")
    __properties: ClassVar[List[str]] = ["deployed_by", "metadata", "ontology_commit_id", "snapshot_rid", "target_branch"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OntologyDeploymentRecordRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OntologyDeploymentRecordRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deployed_by": obj.get("deployed_by"),
            "metadata": obj.get("metadata"),
            "ontology_commit_id": obj.get("ontology_commit_id"),
            "snapshot_rid": obj.get("snapshot_rid"),
            "target_branch": obj.get("target_branch") if obj.get("target_branch") is not None else 'main'
        })
        return _obj


