# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from spice_harvester_sdk.models.query_filter import QueryFilter
from typing import Optional, Set
from typing_extensions import Self

class QueryInput(BaseModel):
    """
    Query input model
    """ # noqa: E501
    class_id: Optional[StrictStr] = None
    class_label: Optional[StrictStr] = None
    filters: Optional[List[QueryFilter]] = Field(default=None, description="Query filters")
    limit: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    order_by: Optional[StrictStr] = None
    order_direction: Optional[StrictStr] = None
    select: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["class_id", "class_label", "filters", "limit", "offset", "order_by", "order_direction", "select"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "class_id": obj.get("class_id"),
            "class_label": obj.get("class_label"),
            "filters": [QueryFilter.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "order_by": obj.get("order_by"),
            "order_direction": obj.get("order_direction"),
            "select": obj.get("select")
        })
        return _obj


