# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SubscriptionCreateRequest(BaseModel):
    """
    SubscriptionCreateRequest
    """ # noqa: E501
    db_name: StrictStr
    notification_channels: Optional[List[StrictStr]] = None
    severity_filter: Optional[List[StrictStr]] = None
    subject_id: StrictStr
    subject_type: Annotated[str, Field(strict=True)]
    __properties: ClassVar[List[str]] = ["db_name", "notification_channels", "severity_filter", "subject_id", "subject_type"]

    @field_validator('subject_type')
    def subject_type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(dataset|mapping_spec|object_type)$", value):
            raise ValueError(r"must validate the regular expression /^(dataset|mapping_spec|object_type)$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "db_name": obj.get("db_name"),
            "notification_channels": obj.get("notification_channels"),
            "severity_filter": obj.get("severity_filter"),
            "subject_id": obj.get("subject_id"),
            "subject_type": obj.get("subject_type")
        })
        return _obj


