# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_harvester_sdk.api.objectify_api import ObjectifyApi


class TestObjectifyApi(unittest.TestCase):
    """ObjectifyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectifyApi()

    def tearDown(self) -> None:
        pass

    def test_create_mapping_spec_api_v1_objectify_mapping_specs_post(self) -> None:
        """Test case for create_mapping_spec_api_v1_objectify_mapping_specs_post

        Create Mapping Spec
        """
        pass

    def test_create_mapping_spec_api_v1_objectify_mapping_specs_post_0(self) -> None:
        """Test case for create_mapping_spec_api_v1_objectify_mapping_specs_post_0

        Create Mapping Spec
        """
        pass

    def test_detect_relationships_api_v1_objectify_databases_db_name_datasets_dataset_id_detect_relationships_post(self) -> None:
        """Test case for detect_relationships_api_v1_objectify_databases_db_name_datasets_dataset_id_detect_relationships_post

        Detect FK relationships in a dataset
        """
        pass

    def test_detect_relationships_api_v1_objectify_databases_db_name_datasets_dataset_id_detect_relationships_post_0(self) -> None:
        """Test case for detect_relationships_api_v1_objectify_databases_db_name_datasets_dataset_id_detect_relationships_post_0

        Detect FK relationships in a dataset
        """
        pass

    def test_get_mapping_spec_watermark_api_v1_objectify_mapping_specs_mapping_spec_id_watermark_get(self) -> None:
        """Test case for get_mapping_spec_watermark_api_v1_objectify_mapping_specs_mapping_spec_id_watermark_get

        Get objectify watermark
        """
        pass

    def test_get_mapping_spec_watermark_api_v1_objectify_mapping_specs_mapping_spec_id_watermark_get_0(self) -> None:
        """Test case for get_mapping_spec_watermark_api_v1_objectify_mapping_specs_mapping_spec_id_watermark_get_0

        Get objectify watermark
        """
        pass

    def test_list_mapping_specs_api_v1_objectify_mapping_specs_get(self) -> None:
        """Test case for list_mapping_specs_api_v1_objectify_mapping_specs_get

        List Mapping Specs
        """
        pass

    def test_list_mapping_specs_api_v1_objectify_mapping_specs_get_0(self) -> None:
        """Test case for list_mapping_specs_api_v1_objectify_mapping_specs_get_0

        List Mapping Specs
        """
        pass

    def test_run_objectify_api_v1_objectify_datasets_dataset_id_run_post(self) -> None:
        """Test case for run_objectify_api_v1_objectify_datasets_dataset_id_run_post

        Run objectify for a single dataset
        """
        pass

    def test_run_objectify_api_v1_objectify_datasets_dataset_id_run_post_0(self) -> None:
        """Test case for run_objectify_api_v1_objectify_datasets_dataset_id_run_post_0

        Run objectify for a single dataset
        """
        pass

    def test_run_objectify_dag_api_v1_objectify_databases_db_name_run_dag_post(self) -> None:
        """Test case for run_objectify_dag_api_v1_objectify_databases_db_name_run_dag_post

        Orchestrate objectify across multiple ontology classes (DAG)
        """
        pass

    def test_run_objectify_dag_api_v1_objectify_databases_db_name_run_dag_post_0(self) -> None:
        """Test case for run_objectify_dag_api_v1_objectify_databases_db_name_run_dag_post_0

        Orchestrate objectify across multiple ontology classes (DAG)
        """
        pass

    def test_trigger_incremental_objectify_api_v1_objectify_mapping_specs_mapping_spec_id_trigger_incremental_post(self) -> None:
        """Test case for trigger_incremental_objectify_api_v1_objectify_mapping_specs_mapping_spec_id_trigger_incremental_post

        Trigger incremental objectify
        """
        pass

    def test_trigger_incremental_objectify_api_v1_objectify_mapping_specs_mapping_spec_id_trigger_incremental_post_0(self) -> None:
        """Test case for trigger_incremental_objectify_api_v1_objectify_mapping_specs_mapping_spec_id_trigger_incremental_post_0

        Trigger incremental objectify
        """
        pass


if __name__ == '__main__':
    unittest.main()
