# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_harvester_sdk.models.graph_query_response import GraphQueryResponse

class TestGraphQueryResponse(unittest.TestCase):
    """GraphQueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GraphQueryResponse:
        """Test GraphQueryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GraphQueryResponse`
        """
        model = GraphQueryResponse()
        if include_optional:
            return GraphQueryResponse(
                base_branch = '',
                count = 56,
                edges = [
                    spice_harvester_sdk.models.graph_edge.GraphEdge(
                        from_node = '', 
                        predicate = '', 
                        provenance = { }, 
                        to_node = '', )
                    ],
                index_summary = { },
                nodes = [
                    spice_harvester_sdk.models.graph_node.GraphNode(
                        data = { }, 
                        data_status = '', 
                        db_name = '', 
                        display = { }, 
                        es_doc_id = '', 
                        es_ref = {
                            'key' : ''
                            }, 
                        id = '', 
                        index_status = { }, 
                        provenance = { }, 
                        type = '', )
                    ],
                overlay_branch = '',
                overlay_status = '',
                page = { },
                paths = [
                    { }
                    ],
                query = { },
                warnings = [
                    ''
                    ],
                writeback_edits_present = True,
                writeback_enabled = True
            )
        else:
            return GraphQueryResponse(
                count = 56,
                edges = [
                    spice_harvester_sdk.models.graph_edge.GraphEdge(
                        from_node = '', 
                        predicate = '', 
                        provenance = { }, 
                        to_node = '', )
                    ],
                nodes = [
                    spice_harvester_sdk.models.graph_node.GraphNode(
                        data = { }, 
                        data_status = '', 
                        db_name = '', 
                        display = { }, 
                        es_doc_id = '', 
                        es_ref = {
                            'key' : ''
                            }, 
                        id = '', 
                        index_status = { }, 
                        provenance = { }, 
                        type = '', )
                    ],
                query = { },
        )
        """

    def testGraphQueryResponse(self):
        """Test GraphQueryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
