# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_harvester_sdk.models.lake_fs_credentials_upsert_request import LakeFSCredentialsUpsertRequest

class TestLakeFSCredentialsUpsertRequest(unittest.TestCase):
    """LakeFSCredentialsUpsertRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LakeFSCredentialsUpsertRequest:
        """Test LakeFSCredentialsUpsertRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LakeFSCredentialsUpsertRequest`
        """
        model = LakeFSCredentialsUpsertRequest()
        if include_optional:
            return LakeFSCredentialsUpsertRequest(
                access_key_id = '',
                principal_id = '',
                principal_type = 'user',
                secret_access_key = ''
            )
        else:
            return LakeFSCredentialsUpsertRequest(
                access_key_id = '',
                principal_id = '',
                principal_type = 'user',
                secret_access_key = '',
        )
        """

    def testLakeFSCredentialsUpsertRequest(self):
        """Test LakeFSCredentialsUpsertRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
