# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_harvester_sdk.models.apply_action_request_options_v2 import ApplyActionRequestOptionsV2

class TestApplyActionRequestOptionsV2(unittest.TestCase):
    """ApplyActionRequestOptionsV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplyActionRequestOptionsV2:
        """Test ApplyActionRequestOptionsV2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplyActionRequestOptionsV2`
        """
        model = ApplyActionRequestOptionsV2()
        if include_optional:
            return ApplyActionRequestOptionsV2(
                mode = '',
                return_edits = ''
            )
        else:
            return ApplyActionRequestOptionsV2(
        )
        """

    def testApplyActionRequestOptionsV2(self):
        """Test ApplyActionRequestOptionsV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
