# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_harvester_sdk.models.ai_intent_route import AIIntentRoute

class TestAIIntentRoute(unittest.TestCase):
    """AIIntentRoute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAIIntentRoute(self):
        """Test AIIntentRoute"""
        # inst = AIIntentRoute()

if __name__ == '__main__':
    unittest.main()
