# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_harvester_sdk.api.summary_api import SummaryApi


class TestSummaryApi(unittest.TestCase):
    """SummaryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SummaryApi()

    def tearDown(self) -> None:
        pass

    def test_get_summary_api_v1_summary_get(self) -> None:
        """Test case for get_summary_api_v1_summary_get

        Get Summary
        """
        pass


if __name__ == '__main__':
    unittest.main()
