# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_harvester_sdk.models.graph_query_request import GraphQueryRequest

class TestGraphQueryRequest(unittest.TestCase):
    """GraphQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GraphQueryRequest:
        """Test GraphQueryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GraphQueryRequest`
        """
        model = GraphQueryRequest()
        if include_optional:
            return GraphQueryRequest(
                filters = { },
                hops = [
                    spice_harvester_sdk.models.graph_hop.GraphHop(
                        predicate = '', 
                        reverse = True, 
                        target_class = '', )
                    ],
                include_audit = True,
                include_documents = True,
                include_paths = True,
                include_provenance = True,
                limit = 56,
                max_edges = 56,
                max_nodes = 56,
                max_paths = 56,
                no_cycles = True,
                offset = 56,
                path_depth_limit = 56,
                start_class = ''
            )
        else:
            return GraphQueryRequest(
                hops = [
                    spice_harvester_sdk.models.graph_hop.GraphHop(
                        predicate = '', 
                        reverse = True, 
                        target_class = '', )
                    ],
                start_class = '',
        )
        """

    def testGraphQueryRequest(self):
        """Test GraphQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
