# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_harvester_sdk.models.trigger_objectify_request import TriggerObjectifyRequest

class TestTriggerObjectifyRequest(unittest.TestCase):
    """TriggerObjectifyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TriggerObjectifyRequest:
        """Test TriggerObjectifyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TriggerObjectifyRequest`
        """
        model = TriggerObjectifyRequest()
        if include_optional:
            return TriggerObjectifyRequest(
                allow_partial = True,
                artifact_id = '',
                artifact_output_name = '',
                batch_size = 56,
                dataset_version_id = '',
                mapping_spec_id = '',
                max_rows = 56,
                options = { },
                target_class_id = ''
            )
        else:
            return TriggerObjectifyRequest(
        )
        """

    def testTriggerObjectifyRequest(self):
        """Test TriggerObjectifyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
