# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_harvester_sdk.models.user_me_response import UserMeResponse

class TestUserMeResponse(unittest.TestCase):
    """UserMeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserMeResponse:
        """Test UserMeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserMeResponse`
        """
        model = UserMeResponse()
        if include_optional:
            return UserMeResponse(
                display_name = '',
                email = '',
                org_id = '',
                roles = [
                    ''
                    ],
                tenant_id = '',
                username = ''
            )
        else:
            return UserMeResponse(
                display_name = '',
                email = '',
                org_id = '',
                roles = [
                    ''
                    ],
                tenant_id = '',
                username = '',
        )
        """

    def testUserMeResponse(self):
        """Test UserMeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
