repos:
  - repo: local
    hooks:
      - id: generate-architecture
        name: Generate Architecture Diagrams
        entry: bash -c "python /Users/isihyeon/Desktop/SPICE\ HARVESTER/generate_architecture.py && git add docs/architecture/"
        language: system
        pass_filenames: false
        always_run: false
        files: '^backend/.*\.py$'
        description: "Automatically generate architecture diagrams when Python files change"