/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetChainHeadApiV1AuditChainHeadGetRequest {
    partitionKey: string;
    lang?: GetChainHeadApiV1AuditChainHeadGetLangEnum;
    acceptLanguage?: string;
}

export interface ListAuditLogsApiV1AuditLogsGetRequest {
    partitionKey?: string;
    action?: string;
    status?: string;
    resourceType?: string;
    resourceId?: string;
    eventId?: string;
    commandId?: string;
    actor?: string;
    since?: Date;
    until?: Date;
    limit?: number;
    offset?: number;
    lang?: ListAuditLogsApiV1AuditLogsGetLangEnum;
    acceptLanguage?: string;
}

/**
 * 
 */
export class AuditApi extends runtime.BaseAPI {

    /**
     * Get Chain Head
     */
    async getChainHeadApiV1AuditChainHeadGetRaw(requestParameters: GetChainHeadApiV1AuditChainHeadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['partitionKey'] == null) {
            throw new runtime.RequiredError(
                'partitionKey',
                'Required parameter "partitionKey" was null or undefined when calling getChainHeadApiV1AuditChainHeadGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['partitionKey'] != null) {
            queryParameters['partition_key'] = requestParameters['partitionKey'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/audit/chain-head`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Chain Head
     */
    async getChainHeadApiV1AuditChainHeadGet(requestParameters: GetChainHeadApiV1AuditChainHeadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getChainHeadApiV1AuditChainHeadGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Audit Logs
     */
    async listAuditLogsApiV1AuditLogsGetRaw(requestParameters: ListAuditLogsApiV1AuditLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['partitionKey'] != null) {
            queryParameters['partition_key'] = requestParameters['partitionKey'];
        }

        if (requestParameters['action'] != null) {
            queryParameters['action'] = requestParameters['action'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['resourceType'] != null) {
            queryParameters['resource_type'] = requestParameters['resourceType'];
        }

        if (requestParameters['resourceId'] != null) {
            queryParameters['resource_id'] = requestParameters['resourceId'];
        }

        if (requestParameters['eventId'] != null) {
            queryParameters['event_id'] = requestParameters['eventId'];
        }

        if (requestParameters['commandId'] != null) {
            queryParameters['command_id'] = requestParameters['commandId'];
        }

        if (requestParameters['actor'] != null) {
            queryParameters['actor'] = requestParameters['actor'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = (requestParameters['since'] as any).toISOString();
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = (requestParameters['until'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/audit/logs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Audit Logs
     */
    async listAuditLogsApiV1AuditLogsGet(requestParameters: ListAuditLogsApiV1AuditLogsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listAuditLogsApiV1AuditLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetChainHeadApiV1AuditChainHeadGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetChainHeadApiV1AuditChainHeadGetLangEnum = typeof GetChainHeadApiV1AuditChainHeadGetLangEnum[keyof typeof GetChainHeadApiV1AuditChainHeadGetLangEnum];
/**
 * @export
 */
export const ListAuditLogsApiV1AuditLogsGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type ListAuditLogsApiV1AuditLogsGetLangEnum = typeof ListAuditLogsApiV1AuditLogsGetLangEnum[keyof typeof ListAuditLogsApiV1AuditLogsGetLangEnum];
