/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface AnalyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetRequest {
    lang?: AnalyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetLangEnum;
    acceptLanguage?: string;
}

export interface AnalyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetRequest {
    compareEnvironment: string;
    lang?: AnalyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetLangEnum;
    acceptLanguage?: string;
}

export interface CheckConfigurationChangesApiV1ConfigConfigCheckChangesPostRequest {
    lang?: CheckConfigurationChangesApiV1ConfigConfigCheckChangesPostLangEnum;
    acceptLanguage?: string;
}

export interface GetConfigurationChangesApiV1ConfigConfigChangesGetRequest {
    limit?: number;
    severity?: string;
    changeType?: string;
    since?: string;
    lang?: GetConfigurationChangesApiV1ConfigConfigChangesGetLangEnum;
    acceptLanguage?: string;
}

export interface GetConfigurationReportApiV1ConfigConfigReportGetRequest {
    lang?: GetConfigurationReportApiV1ConfigConfigReportGetLangEnum;
    acceptLanguage?: string;
}

export interface GetCurrentConfigurationApiV1ConfigConfigCurrentGetRequest {
    includeValidation?: boolean;
    lang?: GetCurrentConfigurationApiV1ConfigConfigCurrentGetLangEnum;
    acceptLanguage?: string;
}

export interface GetMonitoringStatusApiV1ConfigConfigMonitoringStatusGetRequest {
    lang?: GetMonitoringStatusApiV1ConfigConfigMonitoringStatusGetLangEnum;
    acceptLanguage?: string;
}

export interface PerformSecurityAuditApiV1ConfigConfigSecurityAuditGetRequest {
    lang?: PerformSecurityAuditApiV1ConfigConfigSecurityAuditGetLangEnum;
    acceptLanguage?: string;
}

export interface ValidateConfigurationApiV1ConfigConfigValidationGetRequest {
    lang?: ValidateConfigurationApiV1ConfigConfigValidationGetLangEnum;
    acceptLanguage?: string;
}

/**
 * 
 */
export class ConfigMonitoringApi extends runtime.BaseAPI {

    /**
     * Analyze how configuration affects system health
     * Configuration Health Impact
     */
    async analyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetRaw(requestParameters: AnalyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/config/config/health-impact`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Analyze how configuration affects system health
     * Configuration Health Impact
     */
    async analyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGet(requestParameters: AnalyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.analyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Analyze configuration drift between environments
     * Environment Drift Analysis
     */
    async analyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetRaw(requestParameters: AnalyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['compareEnvironment'] == null) {
            throw new runtime.RequiredError(
                'compareEnvironment',
                'Required parameter "compareEnvironment" was null or undefined when calling analyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['compareEnvironment'] != null) {
            queryParameters['compare_environment'] = requestParameters['compareEnvironment'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/config/config/drift-analysis`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Analyze configuration drift between environments
     * Environment Drift Analysis
     */
    async analyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGet(requestParameters: AnalyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.analyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Manually trigger configuration change detection
     * Check for Changes
     */
    async checkConfigurationChangesApiV1ConfigConfigCheckChangesPostRaw(requestParameters: CheckConfigurationChangesApiV1ConfigConfigCheckChangesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/config/config/check-changes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Manually trigger configuration change detection
     * Check for Changes
     */
    async checkConfigurationChangesApiV1ConfigConfigCheckChangesPost(requestParameters: CheckConfigurationChangesApiV1ConfigConfigCheckChangesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.checkConfigurationChangesApiV1ConfigConfigCheckChangesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get configuration change history and detect new changes
     * Configuration Changes
     */
    async getConfigurationChangesApiV1ConfigConfigChangesGetRaw(requestParameters: GetConfigurationChangesApiV1ConfigConfigChangesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['severity'] != null) {
            queryParameters['severity'] = requestParameters['severity'];
        }

        if (requestParameters['changeType'] != null) {
            queryParameters['change_type'] = requestParameters['changeType'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/config/config/changes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get configuration change history and detect new changes
     * Configuration Changes
     */
    async getConfigurationChangesApiV1ConfigConfigChangesGet(requestParameters: GetConfigurationChangesApiV1ConfigConfigChangesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getConfigurationChangesApiV1ConfigConfigChangesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get comprehensive configuration report with all monitoring data
     * Configuration Report
     */
    async getConfigurationReportApiV1ConfigConfigReportGetRaw(requestParameters: GetConfigurationReportApiV1ConfigConfigReportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/config/config/report`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get comprehensive configuration report with all monitoring data
     * Configuration Report
     */
    async getConfigurationReportApiV1ConfigConfigReportGet(requestParameters: GetConfigurationReportApiV1ConfigConfigReportGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getConfigurationReportApiV1ConfigConfigReportGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current application configuration with sensitive values masked
     * Current Configuration
     */
    async getCurrentConfigurationApiV1ConfigConfigCurrentGetRaw(requestParameters: GetCurrentConfigurationApiV1ConfigConfigCurrentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['includeValidation'] != null) {
            queryParameters['include_validation'] = requestParameters['includeValidation'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/config/config/current`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get current application configuration with sensitive values masked
     * Current Configuration
     */
    async getCurrentConfigurationApiV1ConfigConfigCurrentGet(requestParameters: GetCurrentConfigurationApiV1ConfigConfigCurrentGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getCurrentConfigurationApiV1ConfigConfigCurrentGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get status of configuration monitoring system
     * Configuration Monitoring Status
     */
    async getMonitoringStatusApiV1ConfigConfigMonitoringStatusGetRaw(requestParameters: GetMonitoringStatusApiV1ConfigConfigMonitoringStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/config/config/monitoring-status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get status of configuration monitoring system
     * Configuration Monitoring Status
     */
    async getMonitoringStatusApiV1ConfigConfigMonitoringStatusGet(requestParameters: GetMonitoringStatusApiV1ConfigConfigMonitoringStatusGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getMonitoringStatusApiV1ConfigConfigMonitoringStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Perform comprehensive security audit of configuration
     * Security Audit
     */
    async performSecurityAuditApiV1ConfigConfigSecurityAuditGetRaw(requestParameters: PerformSecurityAuditApiV1ConfigConfigSecurityAuditGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/config/config/security-audit`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Perform comprehensive security audit of configuration
     * Security Audit
     */
    async performSecurityAuditApiV1ConfigConfigSecurityAuditGet(requestParameters: PerformSecurityAuditApiV1ConfigConfigSecurityAuditGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.performSecurityAuditApiV1ConfigConfigSecurityAuditGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validate configuration against security and best practice rules
     * Configuration Validation
     */
    async validateConfigurationApiV1ConfigConfigValidationGetRaw(requestParameters: ValidateConfigurationApiV1ConfigConfigValidationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/config/config/validation`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Validate configuration against security and best practice rules
     * Configuration Validation
     */
    async validateConfigurationApiV1ConfigConfigValidationGet(requestParameters: ValidateConfigurationApiV1ConfigConfigValidationGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.validateConfigurationApiV1ConfigConfigValidationGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AnalyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type AnalyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetLangEnum = typeof AnalyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetLangEnum[keyof typeof AnalyzeConfigurationHealthImpactApiV1ConfigConfigHealthImpactGetLangEnum];
/**
 * @export
 */
export const AnalyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type AnalyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetLangEnum = typeof AnalyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetLangEnum[keyof typeof AnalyzeEnvironmentDriftApiV1ConfigConfigDriftAnalysisGetLangEnum];
/**
 * @export
 */
export const CheckConfigurationChangesApiV1ConfigConfigCheckChangesPostLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type CheckConfigurationChangesApiV1ConfigConfigCheckChangesPostLangEnum = typeof CheckConfigurationChangesApiV1ConfigConfigCheckChangesPostLangEnum[keyof typeof CheckConfigurationChangesApiV1ConfigConfigCheckChangesPostLangEnum];
/**
 * @export
 */
export const GetConfigurationChangesApiV1ConfigConfigChangesGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetConfigurationChangesApiV1ConfigConfigChangesGetLangEnum = typeof GetConfigurationChangesApiV1ConfigConfigChangesGetLangEnum[keyof typeof GetConfigurationChangesApiV1ConfigConfigChangesGetLangEnum];
/**
 * @export
 */
export const GetConfigurationReportApiV1ConfigConfigReportGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetConfigurationReportApiV1ConfigConfigReportGetLangEnum = typeof GetConfigurationReportApiV1ConfigConfigReportGetLangEnum[keyof typeof GetConfigurationReportApiV1ConfigConfigReportGetLangEnum];
/**
 * @export
 */
export const GetCurrentConfigurationApiV1ConfigConfigCurrentGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetCurrentConfigurationApiV1ConfigConfigCurrentGetLangEnum = typeof GetCurrentConfigurationApiV1ConfigConfigCurrentGetLangEnum[keyof typeof GetCurrentConfigurationApiV1ConfigConfigCurrentGetLangEnum];
/**
 * @export
 */
export const GetMonitoringStatusApiV1ConfigConfigMonitoringStatusGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetMonitoringStatusApiV1ConfigConfigMonitoringStatusGetLangEnum = typeof GetMonitoringStatusApiV1ConfigConfigMonitoringStatusGetLangEnum[keyof typeof GetMonitoringStatusApiV1ConfigConfigMonitoringStatusGetLangEnum];
/**
 * @export
 */
export const PerformSecurityAuditApiV1ConfigConfigSecurityAuditGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type PerformSecurityAuditApiV1ConfigConfigSecurityAuditGetLangEnum = typeof PerformSecurityAuditApiV1ConfigConfigSecurityAuditGetLangEnum[keyof typeof PerformSecurityAuditApiV1ConfigConfigSecurityAuditGetLangEnum];
/**
 * @export
 */
export const ValidateConfigurationApiV1ConfigConfigValidationGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type ValidateConfigurationApiV1ConfigConfigValidationGetLangEnum = typeof ValidateConfigurationApiV1ConfigConfigValidationGetLangEnum[keyof typeof ValidateConfigurationApiV1ConfigConfigValidationGetLangEnum];
