/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ModelApiResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
} from '../models/index';

export interface ClearMappingsApiV1DatabasesDbNameMappingsDeleteRequest {
    dbName: string;
    lang?: ClearMappingsApiV1DatabasesDbNameMappingsDeleteLangEnum;
    acceptLanguage?: string;
}

export interface ExportMappingsApiV1DatabasesDbNameMappingsExportPostRequest {
    dbName: string;
    lang?: ExportMappingsApiV1DatabasesDbNameMappingsExportPostLangEnum;
    acceptLanguage?: string;
}

export interface GetMappingsSummaryApiV1DatabasesDbNameMappingsGetRequest {
    dbName: string;
    lang?: GetMappingsSummaryApiV1DatabasesDbNameMappingsGetLangEnum;
    acceptLanguage?: string;
}

export interface ImportMappingsApiV1DatabasesDbNameMappingsImportPostRequest {
    dbName: string;
    file: Blob;
    lang?: ImportMappingsApiV1DatabasesDbNameMappingsImportPostLangEnum;
    acceptLanguage?: string;
}

export interface ValidateMappingsApiV1DatabasesDbNameMappingsValidatePostRequest {
    dbName: string;
    file: Blob;
    lang?: ValidateMappingsApiV1DatabasesDbNameMappingsValidatePostLangEnum;
    acceptLanguage?: string;
}

/**
 * 
 */
export class LabelMappingsApi extends runtime.BaseAPI {

    /**
     * Clear Mappings
     */
    async clearMappingsApiV1DatabasesDbNameMappingsDeleteRaw(requestParameters: ClearMappingsApiV1DatabasesDbNameMappingsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['dbName'] == null) {
            throw new runtime.RequiredError(
                'dbName',
                'Required parameter "dbName" was null or undefined when calling clearMappingsApiV1DatabasesDbNameMappingsDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/databases/{db_name}/mappings/`.replace(`{${"db_name"}}`, encodeURIComponent(String(requestParameters['dbName']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Clear Mappings
     */
    async clearMappingsApiV1DatabasesDbNameMappingsDelete(requestParameters: ClearMappingsApiV1DatabasesDbNameMappingsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.clearMappingsApiV1DatabasesDbNameMappingsDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Export Mappings
     */
    async exportMappingsApiV1DatabasesDbNameMappingsExportPostRaw(requestParameters: ExportMappingsApiV1DatabasesDbNameMappingsExportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['dbName'] == null) {
            throw new runtime.RequiredError(
                'dbName',
                'Required parameter "dbName" was null or undefined when calling exportMappingsApiV1DatabasesDbNameMappingsExportPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/databases/{db_name}/mappings/export`.replace(`{${"db_name"}}`, encodeURIComponent(String(requestParameters['dbName']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Export Mappings
     */
    async exportMappingsApiV1DatabasesDbNameMappingsExportPost(requestParameters: ExportMappingsApiV1DatabasesDbNameMappingsExportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.exportMappingsApiV1DatabasesDbNameMappingsExportPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Mappings Summary
     */
    async getMappingsSummaryApiV1DatabasesDbNameMappingsGetRaw(requestParameters: GetMappingsSummaryApiV1DatabasesDbNameMappingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['dbName'] == null) {
            throw new runtime.RequiredError(
                'dbName',
                'Required parameter "dbName" was null or undefined when calling getMappingsSummaryApiV1DatabasesDbNameMappingsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/databases/{db_name}/mappings/`.replace(`{${"db_name"}}`, encodeURIComponent(String(requestParameters['dbName']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Mappings Summary
     */
    async getMappingsSummaryApiV1DatabasesDbNameMappingsGet(requestParameters: GetMappingsSummaryApiV1DatabasesDbNameMappingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getMappingsSummaryApiV1DatabasesDbNameMappingsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Mappings
     */
    async importMappingsApiV1DatabasesDbNameMappingsImportPostRaw(requestParameters: ImportMappingsApiV1DatabasesDbNameMappingsImportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters['dbName'] == null) {
            throw new runtime.RequiredError(
                'dbName',
                'Required parameter "dbName" was null or undefined when calling importMappingsApiV1DatabasesDbNameMappingsImportPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling importMappingsApiV1DatabasesDbNameMappingsImportPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/v1/databases/{db_name}/mappings/import`.replace(`{${"db_name"}}`, encodeURIComponent(String(requestParameters['dbName']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Import Mappings
     */
    async importMappingsApiV1DatabasesDbNameMappingsImportPost(requestParameters: ImportMappingsApiV1DatabasesDbNameMappingsImportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.importMappingsApiV1DatabasesDbNameMappingsImportPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validate Mappings
     */
    async validateMappingsApiV1DatabasesDbNameMappingsValidatePostRaw(requestParameters: ValidateMappingsApiV1DatabasesDbNameMappingsValidatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters['dbName'] == null) {
            throw new runtime.RequiredError(
                'dbName',
                'Required parameter "dbName" was null or undefined when calling validateMappingsApiV1DatabasesDbNameMappingsValidatePost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling validateMappingsApiV1DatabasesDbNameMappingsValidatePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/v1/databases/{db_name}/mappings/validate`.replace(`{${"db_name"}}`, encodeURIComponent(String(requestParameters['dbName']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Validate Mappings
     */
    async validateMappingsApiV1DatabasesDbNameMappingsValidatePost(requestParameters: ValidateMappingsApiV1DatabasesDbNameMappingsValidatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.validateMappingsApiV1DatabasesDbNameMappingsValidatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ClearMappingsApiV1DatabasesDbNameMappingsDeleteLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type ClearMappingsApiV1DatabasesDbNameMappingsDeleteLangEnum = typeof ClearMappingsApiV1DatabasesDbNameMappingsDeleteLangEnum[keyof typeof ClearMappingsApiV1DatabasesDbNameMappingsDeleteLangEnum];
/**
 * @export
 */
export const ExportMappingsApiV1DatabasesDbNameMappingsExportPostLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type ExportMappingsApiV1DatabasesDbNameMappingsExportPostLangEnum = typeof ExportMappingsApiV1DatabasesDbNameMappingsExportPostLangEnum[keyof typeof ExportMappingsApiV1DatabasesDbNameMappingsExportPostLangEnum];
/**
 * @export
 */
export const GetMappingsSummaryApiV1DatabasesDbNameMappingsGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetMappingsSummaryApiV1DatabasesDbNameMappingsGetLangEnum = typeof GetMappingsSummaryApiV1DatabasesDbNameMappingsGetLangEnum[keyof typeof GetMappingsSummaryApiV1DatabasesDbNameMappingsGetLangEnum];
/**
 * @export
 */
export const ImportMappingsApiV1DatabasesDbNameMappingsImportPostLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type ImportMappingsApiV1DatabasesDbNameMappingsImportPostLangEnum = typeof ImportMappingsApiV1DatabasesDbNameMappingsImportPostLangEnum[keyof typeof ImportMappingsApiV1DatabasesDbNameMappingsImportPostLangEnum];
/**
 * @export
 */
export const ValidateMappingsApiV1DatabasesDbNameMappingsValidatePostLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type ValidateMappingsApiV1DatabasesDbNameMappingsValidatePostLangEnum = typeof ValidateMappingsApiV1DatabasesDbNameMappingsValidatePostLangEnum[keyof typeof ValidateMappingsApiV1DatabasesDbNameMappingsValidatePostLangEnum];
