/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetLineageColumnLineageApiV1LineageColumnLineageGetRequest {
    dbName?: string;
    branch?: string;
    runId?: string;
    sourceField?: string;
    targetField?: string;
    targetClassId?: string;
    since?: Date;
    until?: Date;
    edgeLimit?: number;
    pairLimit?: number;
    lang?: GetLineageColumnLineageApiV1LineageColumnLineageGetLangEnum;
    acceptLanguage?: string;
}

export interface GetLineageDiffApiV1LineageDiffGetRequest {
    root: string;
    fromAsOf: Date;
    toAsOf?: Date;
    dbName?: string;
    branch?: string;
    direction?: GetLineageDiffApiV1LineageDiffGetDirectionEnum;
    maxDepth?: number;
    maxNodes?: number;
    maxEdges?: number;
    lang?: GetLineageDiffApiV1LineageDiffGetLangEnum;
    acceptLanguage?: string;
}

export interface GetLineageGraphApiV1LineageGraphGetRequest {
    root: string;
    dbName?: string;
    branch?: string;
    asOf?: Date;
    direction?: GetLineageGraphApiV1LineageGraphGetDirectionEnum;
    maxDepth?: number;
    maxNodes?: number;
    maxEdges?: number;
    lang?: GetLineageGraphApiV1LineageGraphGetLangEnum;
    acceptLanguage?: string;
}

export interface GetLineageImpactApiV1LineageImpactGetRequest {
    root: string;
    dbName?: string;
    branch?: string;
    asOf?: Date;
    direction?: GetLineageImpactApiV1LineageImpactGetDirectionEnum;
    maxDepth?: number;
    artifactKind?: string;
    maxNodes?: number;
    maxEdges?: number;
    lang?: GetLineageImpactApiV1LineageImpactGetLangEnum;
    acceptLanguage?: string;
}

export interface GetLineageMetricsApiV1LineageMetricsGetRequest {
    dbName?: string;
    branch?: string;
    windowMinutes?: number;
    lang?: GetLineageMetricsApiV1LineageMetricsGetLangEnum;
    acceptLanguage?: string;
}

export interface GetLineageOutOfDateApiV1LineageOutOfDateGetRequest {
    dbName?: string;
    branch?: string;
    artifactKind?: string;
    asOf?: Date;
    freshnessSloMinutes?: number;
    artifactLimit?: number;
    stalePreviewLimit?: number;
    projectionLimit?: number;
    projectionPreviewLimit?: number;
    lang?: GetLineageOutOfDateApiV1LineageOutOfDateGetLangEnum;
    acceptLanguage?: string;
}

export interface GetLineagePathApiV1LineagePathGetRequest {
    source: string;
    target: string;
    dbName?: string;
    branch?: string;
    asOf?: Date;
    direction?: GetLineagePathApiV1LineagePathGetDirectionEnum;
    maxDepth?: number;
    maxNodes?: number;
    maxEdges?: number;
    lang?: GetLineagePathApiV1LineagePathGetLangEnum;
    acceptLanguage?: string;
}

export interface GetLineageRunImpactApiV1LineageRunImpactGetRequest {
    runId: string;
    dbName?: string;
    branch?: string;
    since?: Date;
    until?: Date;
    eventLimit?: number;
    artifactPreviewLimit?: number;
    lang?: GetLineageRunImpactApiV1LineageRunImpactGetLangEnum;
    acceptLanguage?: string;
}

export interface GetLineageRunsApiV1LineageRunsGetRequest {
    dbName?: string;
    branch?: string;
    since?: Date;
    until?: Date;
    edgeType?: string;
    runLimit?: number;
    freshnessSloMinutes?: number;
    includeImpactPreview?: boolean;
    impactPreviewRunsLimit?: number;
    impactPreviewArtifactsLimit?: number;
    impactPreviewEdgeLimit?: number;
    lang?: GetLineageRunsApiV1LineageRunsGetLangEnum;
    acceptLanguage?: string;
}

export interface GetLineageTimelineApiV1LineageTimelineGetRequest {
    dbName?: string;
    branch?: string;
    since?: Date;
    until?: Date;
    edgeType?: string;
    projectionName?: string;
    bucketMinutes?: number;
    eventLimit?: number;
    eventPreviewLimit?: number;
    lang?: GetLineageTimelineApiV1LineageTimelineGetLangEnum;
    acceptLanguage?: string;
}

/**
 * 
 */
export class LineageApi extends runtime.BaseAPI {

    /**
     * Resolve column-level lineage from mapping-spec references embedded in lineage edges.  This provides a Foundry-style \"which source columns mapped to which target fields\" view without exploding the graph into per-column nodes.
     * Get Lineage Column Lineage
     */
    async getLineageColumnLineageApiV1LineageColumnLineageGetRaw(requestParameters: GetLineageColumnLineageApiV1LineageColumnLineageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['runId'] != null) {
            queryParameters['run_id'] = requestParameters['runId'];
        }

        if (requestParameters['sourceField'] != null) {
            queryParameters['source_field'] = requestParameters['sourceField'];
        }

        if (requestParameters['targetField'] != null) {
            queryParameters['target_field'] = requestParameters['targetField'];
        }

        if (requestParameters['targetClassId'] != null) {
            queryParameters['target_class_id'] = requestParameters['targetClassId'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = (requestParameters['since'] as any).toISOString();
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = (requestParameters['until'] as any).toISOString();
        }

        if (requestParameters['edgeLimit'] != null) {
            queryParameters['edge_limit'] = requestParameters['edgeLimit'];
        }

        if (requestParameters['pairLimit'] != null) {
            queryParameters['pair_limit'] = requestParameters['pairLimit'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/column-lineage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Resolve column-level lineage from mapping-spec references embedded in lineage edges.  This provides a Foundry-style \"which source columns mapped to which target fields\" view without exploding the graph into per-column nodes.
     * Get Lineage Column Lineage
     */
    async getLineageColumnLineageApiV1LineageColumnLineageGet(requestParameters: GetLineageColumnLineageApiV1LineageColumnLineageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineageColumnLineageApiV1LineageColumnLineageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Lineage Diff
     */
    async getLineageDiffApiV1LineageDiffGetRaw(requestParameters: GetLineageDiffApiV1LineageDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['root'] == null) {
            throw new runtime.RequiredError(
                'root',
                'Required parameter "root" was null or undefined when calling getLineageDiffApiV1LineageDiffGet().'
            );
        }

        if (requestParameters['fromAsOf'] == null) {
            throw new runtime.RequiredError(
                'fromAsOf',
                'Required parameter "fromAsOf" was null or undefined when calling getLineageDiffApiV1LineageDiffGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['root'] != null) {
            queryParameters['root'] = requestParameters['root'];
        }

        if (requestParameters['fromAsOf'] != null) {
            queryParameters['from_as_of'] = (requestParameters['fromAsOf'] as any).toISOString();
        }

        if (requestParameters['toAsOf'] != null) {
            queryParameters['to_as_of'] = (requestParameters['toAsOf'] as any).toISOString();
        }

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['maxDepth'] != null) {
            queryParameters['max_depth'] = requestParameters['maxDepth'];
        }

        if (requestParameters['maxNodes'] != null) {
            queryParameters['max_nodes'] = requestParameters['maxNodes'];
        }

        if (requestParameters['maxEdges'] != null) {
            queryParameters['max_edges'] = requestParameters['maxEdges'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/diff`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Lineage Diff
     */
    async getLineageDiffApiV1LineageDiffGet(requestParameters: GetLineageDiffApiV1LineageDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineageDiffApiV1LineageDiffGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Lineage Graph
     */
    async getLineageGraphApiV1LineageGraphGetRaw(requestParameters: GetLineageGraphApiV1LineageGraphGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['root'] == null) {
            throw new runtime.RequiredError(
                'root',
                'Required parameter "root" was null or undefined when calling getLineageGraphApiV1LineageGraphGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['root'] != null) {
            queryParameters['root'] = requestParameters['root'];
        }

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['asOf'] != null) {
            queryParameters['as_of'] = (requestParameters['asOf'] as any).toISOString();
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['maxDepth'] != null) {
            queryParameters['max_depth'] = requestParameters['maxDepth'];
        }

        if (requestParameters['maxNodes'] != null) {
            queryParameters['max_nodes'] = requestParameters['maxNodes'];
        }

        if (requestParameters['maxEdges'] != null) {
            queryParameters['max_edges'] = requestParameters['maxEdges'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/graph`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Lineage Graph
     */
    async getLineageGraphApiV1LineageGraphGet(requestParameters: GetLineageGraphApiV1LineageGraphGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineageGraphApiV1LineageGraphGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Lineage Impact
     */
    async getLineageImpactApiV1LineageImpactGetRaw(requestParameters: GetLineageImpactApiV1LineageImpactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['root'] == null) {
            throw new runtime.RequiredError(
                'root',
                'Required parameter "root" was null or undefined when calling getLineageImpactApiV1LineageImpactGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['root'] != null) {
            queryParameters['root'] = requestParameters['root'];
        }

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['asOf'] != null) {
            queryParameters['as_of'] = (requestParameters['asOf'] as any).toISOString();
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['maxDepth'] != null) {
            queryParameters['max_depth'] = requestParameters['maxDepth'];
        }

        if (requestParameters['artifactKind'] != null) {
            queryParameters['artifact_kind'] = requestParameters['artifactKind'];
        }

        if (requestParameters['maxNodes'] != null) {
            queryParameters['max_nodes'] = requestParameters['maxNodes'];
        }

        if (requestParameters['maxEdges'] != null) {
            queryParameters['max_edges'] = requestParameters['maxEdges'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/impact`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Lineage Impact
     */
    async getLineageImpactApiV1LineageImpactGet(requestParameters: GetLineageImpactApiV1LineageImpactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineageImpactApiV1LineageImpactGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Operational lineage metrics.  - `lineage_lag_seconds`: age of oldest missing-lineage item in the backfill queue - `missing_lineage_ratio_estimate`: based on EVENT_APPENDED audit count vs recorded lineage edges
     * Get Lineage Metrics
     */
    async getLineageMetricsApiV1LineageMetricsGetRaw(requestParameters: GetLineageMetricsApiV1LineageMetricsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['windowMinutes'] != null) {
            queryParameters['window_minutes'] = requestParameters['windowMinutes'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/metrics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Operational lineage metrics.  - `lineage_lag_seconds`: age of oldest missing-lineage item in the backfill queue - `missing_lineage_ratio_estimate`: based on EVENT_APPENDED audit count vs recorded lineage edges
     * Get Lineage Metrics
     */
    async getLineageMetricsApiV1LineageMetricsGet(requestParameters: GetLineageMetricsApiV1LineageMetricsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineageMetricsApiV1LineageMetricsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Foundry-style out-of-date diagnostics: - identify stale artifacts/projections by latest lineage write time - provide actionable blast-radius remediation hints
     * Get Lineage Out Of Date
     */
    async getLineageOutOfDateApiV1LineageOutOfDateGetRaw(requestParameters: GetLineageOutOfDateApiV1LineageOutOfDateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['artifactKind'] != null) {
            queryParameters['artifact_kind'] = requestParameters['artifactKind'];
        }

        if (requestParameters['asOf'] != null) {
            queryParameters['as_of'] = (requestParameters['asOf'] as any).toISOString();
        }

        if (requestParameters['freshnessSloMinutes'] != null) {
            queryParameters['freshness_slo_minutes'] = requestParameters['freshnessSloMinutes'];
        }

        if (requestParameters['artifactLimit'] != null) {
            queryParameters['artifact_limit'] = requestParameters['artifactLimit'];
        }

        if (requestParameters['stalePreviewLimit'] != null) {
            queryParameters['stale_preview_limit'] = requestParameters['stalePreviewLimit'];
        }

        if (requestParameters['projectionLimit'] != null) {
            queryParameters['projection_limit'] = requestParameters['projectionLimit'];
        }

        if (requestParameters['projectionPreviewLimit'] != null) {
            queryParameters['projection_preview_limit'] = requestParameters['projectionPreviewLimit'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/out-of-date`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Foundry-style out-of-date diagnostics: - identify stale artifacts/projections by latest lineage write time - provide actionable blast-radius remediation hints
     * Get Lineage Out Of Date
     */
    async getLineageOutOfDateApiV1LineageOutOfDateGet(requestParameters: GetLineageOutOfDateApiV1LineageOutOfDateGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineageOutOfDateApiV1LineageOutOfDateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Lineage Path
     */
    async getLineagePathApiV1LineagePathGetRaw(requestParameters: GetLineagePathApiV1LineagePathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['source'] == null) {
            throw new runtime.RequiredError(
                'source',
                'Required parameter "source" was null or undefined when calling getLineagePathApiV1LineagePathGet().'
            );
        }

        if (requestParameters['target'] == null) {
            throw new runtime.RequiredError(
                'target',
                'Required parameter "target" was null or undefined when calling getLineagePathApiV1LineagePathGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['source'] != null) {
            queryParameters['source'] = requestParameters['source'];
        }

        if (requestParameters['target'] != null) {
            queryParameters['target'] = requestParameters['target'];
        }

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['asOf'] != null) {
            queryParameters['as_of'] = (requestParameters['asOf'] as any).toISOString();
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['maxDepth'] != null) {
            queryParameters['max_depth'] = requestParameters['maxDepth'];
        }

        if (requestParameters['maxNodes'] != null) {
            queryParameters['max_nodes'] = requestParameters['maxNodes'];
        }

        if (requestParameters['maxEdges'] != null) {
            queryParameters['max_edges'] = requestParameters['maxEdges'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/path`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Lineage Path
     */
    async getLineagePathApiV1LineagePathGet(requestParameters: GetLineagePathApiV1LineagePathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineagePathApiV1LineagePathGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Foundry-style run/build impact diagnostics. Answers: \"this run touched what, when, and with what blast radius?\"
     * Get Lineage Run Impact
     */
    async getLineageRunImpactApiV1LineageRunImpactGetRaw(requestParameters: GetLineageRunImpactApiV1LineageRunImpactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getLineageRunImpactApiV1LineageRunImpactGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['runId'] != null) {
            queryParameters['run_id'] = requestParameters['runId'];
        }

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = (requestParameters['since'] as any).toISOString();
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = (requestParameters['until'] as any).toISOString();
        }

        if (requestParameters['eventLimit'] != null) {
            queryParameters['event_limit'] = requestParameters['eventLimit'];
        }

        if (requestParameters['artifactPreviewLimit'] != null) {
            queryParameters['artifact_preview_limit'] = requestParameters['artifactPreviewLimit'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/run-impact`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Foundry-style run/build impact diagnostics. Answers: \"this run touched what, when, and with what blast radius?\"
     * Get Lineage Run Impact
     */
    async getLineageRunImpactApiV1LineageRunImpactGet(requestParameters: GetLineageRunImpactApiV1LineageRunImpactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineageRunImpactApiV1LineageRunImpactGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Foundry-style build/run timeline: - run windows (first/last activity) - per-run blast-radius stats - optional impacted artifact previews
     * Get Lineage Runs
     */
    async getLineageRunsApiV1LineageRunsGetRaw(requestParameters: GetLineageRunsApiV1LineageRunsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = (requestParameters['since'] as any).toISOString();
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = (requestParameters['until'] as any).toISOString();
        }

        if (requestParameters['edgeType'] != null) {
            queryParameters['edge_type'] = requestParameters['edgeType'];
        }

        if (requestParameters['runLimit'] != null) {
            queryParameters['run_limit'] = requestParameters['runLimit'];
        }

        if (requestParameters['freshnessSloMinutes'] != null) {
            queryParameters['freshness_slo_minutes'] = requestParameters['freshnessSloMinutes'];
        }

        if (requestParameters['includeImpactPreview'] != null) {
            queryParameters['include_impact_preview'] = requestParameters['includeImpactPreview'];
        }

        if (requestParameters['impactPreviewRunsLimit'] != null) {
            queryParameters['impact_preview_runs_limit'] = requestParameters['impactPreviewRunsLimit'];
        }

        if (requestParameters['impactPreviewArtifactsLimit'] != null) {
            queryParameters['impact_preview_artifacts_limit'] = requestParameters['impactPreviewArtifactsLimit'];
        }

        if (requestParameters['impactPreviewEdgeLimit'] != null) {
            queryParameters['impact_preview_edge_limit'] = requestParameters['impactPreviewEdgeLimit'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/runs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Foundry-style build/run timeline: - run windows (first/last activity) - per-run blast-radius stats - optional impacted artifact previews
     * Get Lineage Runs
     */
    async getLineageRunsApiV1LineageRunsGet(requestParameters: GetLineageRunsApiV1LineageRunsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineageRunsApiV1LineageRunsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Foundry-style lineage timeline for operational debugging: - when lineage events spiked - which edge/projection/service dominated
     * Get Lineage Timeline
     */
    async getLineageTimelineApiV1LineageTimelineGetRaw(requestParameters: GetLineageTimelineApiV1LineageTimelineGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['dbName'] != null) {
            queryParameters['db_name'] = requestParameters['dbName'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = (requestParameters['since'] as any).toISOString();
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = (requestParameters['until'] as any).toISOString();
        }

        if (requestParameters['edgeType'] != null) {
            queryParameters['edge_type'] = requestParameters['edgeType'];
        }

        if (requestParameters['projectionName'] != null) {
            queryParameters['projection_name'] = requestParameters['projectionName'];
        }

        if (requestParameters['bucketMinutes'] != null) {
            queryParameters['bucket_minutes'] = requestParameters['bucketMinutes'];
        }

        if (requestParameters['eventLimit'] != null) {
            queryParameters['event_limit'] = requestParameters['eventLimit'];
        }

        if (requestParameters['eventPreviewLimit'] != null) {
            queryParameters['event_preview_limit'] = requestParameters['eventPreviewLimit'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/lineage/timeline`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Foundry-style lineage timeline for operational debugging: - when lineage events spiked - which edge/projection/service dominated
     * Get Lineage Timeline
     */
    async getLineageTimelineApiV1LineageTimelineGet(requestParameters: GetLineageTimelineApiV1LineageTimelineGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getLineageTimelineApiV1LineageTimelineGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetLineageColumnLineageApiV1LineageColumnLineageGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineageColumnLineageApiV1LineageColumnLineageGetLangEnum = typeof GetLineageColumnLineageApiV1LineageColumnLineageGetLangEnum[keyof typeof GetLineageColumnLineageApiV1LineageColumnLineageGetLangEnum];
/**
 * @export
 */
export const GetLineageDiffApiV1LineageDiffGetDirectionEnum = {
    Upstream: 'upstream',
    Downstream: 'downstream',
    Both: 'both'
} as const;
export type GetLineageDiffApiV1LineageDiffGetDirectionEnum = typeof GetLineageDiffApiV1LineageDiffGetDirectionEnum[keyof typeof GetLineageDiffApiV1LineageDiffGetDirectionEnum];
/**
 * @export
 */
export const GetLineageDiffApiV1LineageDiffGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineageDiffApiV1LineageDiffGetLangEnum = typeof GetLineageDiffApiV1LineageDiffGetLangEnum[keyof typeof GetLineageDiffApiV1LineageDiffGetLangEnum];
/**
 * @export
 */
export const GetLineageGraphApiV1LineageGraphGetDirectionEnum = {
    Upstream: 'upstream',
    Downstream: 'downstream',
    Both: 'both'
} as const;
export type GetLineageGraphApiV1LineageGraphGetDirectionEnum = typeof GetLineageGraphApiV1LineageGraphGetDirectionEnum[keyof typeof GetLineageGraphApiV1LineageGraphGetDirectionEnum];
/**
 * @export
 */
export const GetLineageGraphApiV1LineageGraphGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineageGraphApiV1LineageGraphGetLangEnum = typeof GetLineageGraphApiV1LineageGraphGetLangEnum[keyof typeof GetLineageGraphApiV1LineageGraphGetLangEnum];
/**
 * @export
 */
export const GetLineageImpactApiV1LineageImpactGetDirectionEnum = {
    Upstream: 'upstream',
    Downstream: 'downstream',
    Both: 'both'
} as const;
export type GetLineageImpactApiV1LineageImpactGetDirectionEnum = typeof GetLineageImpactApiV1LineageImpactGetDirectionEnum[keyof typeof GetLineageImpactApiV1LineageImpactGetDirectionEnum];
/**
 * @export
 */
export const GetLineageImpactApiV1LineageImpactGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineageImpactApiV1LineageImpactGetLangEnum = typeof GetLineageImpactApiV1LineageImpactGetLangEnum[keyof typeof GetLineageImpactApiV1LineageImpactGetLangEnum];
/**
 * @export
 */
export const GetLineageMetricsApiV1LineageMetricsGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineageMetricsApiV1LineageMetricsGetLangEnum = typeof GetLineageMetricsApiV1LineageMetricsGetLangEnum[keyof typeof GetLineageMetricsApiV1LineageMetricsGetLangEnum];
/**
 * @export
 */
export const GetLineageOutOfDateApiV1LineageOutOfDateGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineageOutOfDateApiV1LineageOutOfDateGetLangEnum = typeof GetLineageOutOfDateApiV1LineageOutOfDateGetLangEnum[keyof typeof GetLineageOutOfDateApiV1LineageOutOfDateGetLangEnum];
/**
 * @export
 */
export const GetLineagePathApiV1LineagePathGetDirectionEnum = {
    Upstream: 'upstream',
    Downstream: 'downstream',
    Both: 'both'
} as const;
export type GetLineagePathApiV1LineagePathGetDirectionEnum = typeof GetLineagePathApiV1LineagePathGetDirectionEnum[keyof typeof GetLineagePathApiV1LineagePathGetDirectionEnum];
/**
 * @export
 */
export const GetLineagePathApiV1LineagePathGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineagePathApiV1LineagePathGetLangEnum = typeof GetLineagePathApiV1LineagePathGetLangEnum[keyof typeof GetLineagePathApiV1LineagePathGetLangEnum];
/**
 * @export
 */
export const GetLineageRunImpactApiV1LineageRunImpactGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineageRunImpactApiV1LineageRunImpactGetLangEnum = typeof GetLineageRunImpactApiV1LineageRunImpactGetLangEnum[keyof typeof GetLineageRunImpactApiV1LineageRunImpactGetLangEnum];
/**
 * @export
 */
export const GetLineageRunsApiV1LineageRunsGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineageRunsApiV1LineageRunsGetLangEnum = typeof GetLineageRunsApiV1LineageRunsGetLangEnum[keyof typeof GetLineageRunsApiV1LineageRunsGetLangEnum];
/**
 * @export
 */
export const GetLineageTimelineApiV1LineageTimelineGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetLineageTimelineApiV1LineageTimelineGetLangEnum = typeof GetLineageTimelineApiV1LineageTimelineGetLangEnum[keyof typeof GetLineageTimelineApiV1LineageTimelineGetLangEnum];
