/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateMappingSpecRequest,
  DetectRelationshipsRequest,
  HTTPValidationError,
  RunObjectifyDAGRequest,
  TriggerIncrementalRequest,
  TriggerObjectifyRequest,
} from '../models/index';
import {
    CreateMappingSpecRequestFromJSON,
    CreateMappingSpecRequestToJSON,
    DetectRelationshipsRequestFromJSON,
    DetectRelationshipsRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    RunObjectifyDAGRequestFromJSON,
    RunObjectifyDAGRequestToJSON,
    TriggerIncrementalRequestFromJSON,
    TriggerIncrementalRequestToJSON,
    TriggerObjectifyRequestFromJSON,
    TriggerObjectifyRequestToJSON,
} from '../models/index';

export interface CreateMappingSpecApiV1ObjectifyMappingSpecsPostRequest {
    createMappingSpecRequest: CreateMappingSpecRequest;
    lang?: CreateMappingSpecApiV1ObjectifyMappingSpecsPostLangEnum;
    acceptLanguage?: string;
}

export interface CreateMappingSpecApiV1ObjectifyMappingSpecsPost0Request {
    createMappingSpecRequest: CreateMappingSpecRequest;
    lang?: CreateMappingSpecApiV1ObjectifyMappingSpecsPost0LangEnum;
    acceptLanguage?: string;
}

export interface DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostRequest {
    dbName: string;
    datasetId: string;
    branch?: string;
    lang?: DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostLangEnum;
    acceptLanguage?: string;
    detectRelationshipsRequest?: DetectRelationshipsRequest;
}

export interface DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost0Request {
    dbName: string;
    datasetId: string;
    branch?: string;
    lang?: DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost0LangEnum;
    acceptLanguage?: string;
    detectRelationshipsRequest?: DetectRelationshipsRequest;
}

export interface GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetRequest {
    mappingSpecId: string;
    branch?: string;
    lang?: GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetLangEnum;
    acceptLanguage?: string;
}

export interface GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet0Request {
    mappingSpecId: string;
    branch?: string;
    lang?: GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet0LangEnum;
    acceptLanguage?: string;
}

export interface ListMappingSpecsApiV1ObjectifyMappingSpecsGetRequest {
    datasetId?: string;
    includeInactive?: boolean;
    lang?: ListMappingSpecsApiV1ObjectifyMappingSpecsGetLangEnum;
    acceptLanguage?: string;
}

export interface ListMappingSpecsApiV1ObjectifyMappingSpecsGet0Request {
    datasetId?: string;
    includeInactive?: boolean;
    lang?: ListMappingSpecsApiV1ObjectifyMappingSpecsGet0LangEnum;
    acceptLanguage?: string;
}

export interface RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostRequest {
    datasetId: string;
    triggerObjectifyRequest: TriggerObjectifyRequest;
    lang?: RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostLangEnum;
    acceptLanguage?: string;
}

export interface RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost0Request {
    datasetId: string;
    triggerObjectifyRequest: TriggerObjectifyRequest;
    lang?: RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost0LangEnum;
    acceptLanguage?: string;
}

export interface RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostRequest {
    dbName: string;
    runObjectifyDAGRequest: RunObjectifyDAGRequest;
    lang?: RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostLangEnum;
    acceptLanguage?: string;
}

export interface RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost0Request {
    dbName: string;
    runObjectifyDAGRequest: RunObjectifyDAGRequest;
    lang?: RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost0LangEnum;
    acceptLanguage?: string;
}

export interface TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostRequest {
    mappingSpecId: string;
    branch?: string;
    lang?: TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostLangEnum;
    acceptLanguage?: string;
    triggerIncrementalRequest?: TriggerIncrementalRequest;
}

export interface TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost0Request {
    mappingSpecId: string;
    branch?: string;
    lang?: TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost0LangEnum;
    acceptLanguage?: string;
    triggerIncrementalRequest?: TriggerIncrementalRequest;
}

/**
 * 
 */
export class ObjectifyApi extends runtime.BaseAPI {

    /**
     * Create Mapping Spec
     */
    async createMappingSpecApiV1ObjectifyMappingSpecsPostRaw(requestParameters: CreateMappingSpecApiV1ObjectifyMappingSpecsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['createMappingSpecRequest'] == null) {
            throw new runtime.RequiredError(
                'createMappingSpecRequest',
                'Required parameter "createMappingSpecRequest" was null or undefined when calling createMappingSpecApiV1ObjectifyMappingSpecsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/mapping-specs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMappingSpecRequestToJSON(requestParameters['createMappingSpecRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create Mapping Spec
     */
    async createMappingSpecApiV1ObjectifyMappingSpecsPost(requestParameters: CreateMappingSpecApiV1ObjectifyMappingSpecsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createMappingSpecApiV1ObjectifyMappingSpecsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Mapping Spec
     */
    async createMappingSpecApiV1ObjectifyMappingSpecsPost_1Raw(requestParameters: CreateMappingSpecApiV1ObjectifyMappingSpecsPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['createMappingSpecRequest'] == null) {
            throw new runtime.RequiredError(
                'createMappingSpecRequest',
                'Required parameter "createMappingSpecRequest" was null or undefined when calling createMappingSpecApiV1ObjectifyMappingSpecsPost_1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/mapping-specs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMappingSpecRequestToJSON(requestParameters['createMappingSpecRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create Mapping Spec
     */
    async createMappingSpecApiV1ObjectifyMappingSpecsPost_1(requestParameters: CreateMappingSpecApiV1ObjectifyMappingSpecsPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createMappingSpecApiV1ObjectifyMappingSpecsPost_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Analyzes dataset columns to detect potential foreign key relationships based on naming conventions and value overlap.
     * Detect FK relationships in a dataset
     */
    async detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostRaw(requestParameters: DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['dbName'] == null) {
            throw new runtime.RequiredError(
                'dbName',
                'Required parameter "dbName" was null or undefined when calling detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost().'
            );
        }

        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/databases/{db_name}/datasets/{dataset_id}/detect-relationships`.replace(`{${"db_name"}}`, encodeURIComponent(String(requestParameters['dbName']))).replace(`{${"dataset_id"}}`, encodeURIComponent(String(requestParameters['datasetId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DetectRelationshipsRequestToJSON(requestParameters['detectRelationshipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Analyzes dataset columns to detect potential foreign key relationships based on naming conventions and value overlap.
     * Detect FK relationships in a dataset
     */
    async detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost(requestParameters: DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Analyzes dataset columns to detect potential foreign key relationships based on naming conventions and value overlap.
     * Detect FK relationships in a dataset
     */
    async detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost_2Raw(requestParameters: DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['dbName'] == null) {
            throw new runtime.RequiredError(
                'dbName',
                'Required parameter "dbName" was null or undefined when calling detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost_2().'
            );
        }

        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost_2().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/databases/{db_name}/datasets/{dataset_id}/detect-relationships`.replace(`{${"db_name"}}`, encodeURIComponent(String(requestParameters['dbName']))).replace(`{${"dataset_id"}}`, encodeURIComponent(String(requestParameters['datasetId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DetectRelationshipsRequestToJSON(requestParameters['detectRelationshipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Analyzes dataset columns to detect potential foreign key relationships based on naming conventions and value overlap.
     * Detect FK relationships in a dataset
     */
    async detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost_2(requestParameters: DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.detectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the current watermark state for a mapping spec.
     * Get objectify watermark
     */
    async getMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetRaw(requestParameters: GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['mappingSpecId'] == null) {
            throw new runtime.RequiredError(
                'mappingSpecId',
                'Required parameter "mappingSpecId" was null or undefined when calling getMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/mapping-specs/{mapping_spec_id}/watermark`.replace(`{${"mapping_spec_id"}}`, encodeURIComponent(String(requestParameters['mappingSpecId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the current watermark state for a mapping spec.
     * Get objectify watermark
     */
    async getMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet(requestParameters: GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the current watermark state for a mapping spec.
     * Get objectify watermark
     */
    async getMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet_3Raw(requestParameters: GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['mappingSpecId'] == null) {
            throw new runtime.RequiredError(
                'mappingSpecId',
                'Required parameter "mappingSpecId" was null or undefined when calling getMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet_3().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/mapping-specs/{mapping_spec_id}/watermark`.replace(`{${"mapping_spec_id"}}`, encodeURIComponent(String(requestParameters['mappingSpecId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the current watermark state for a mapping spec.
     * Get objectify watermark
     */
    async getMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet_3(requestParameters: GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Mapping Specs
     */
    async listMappingSpecsApiV1ObjectifyMappingSpecsGetRaw(requestParameters: ListMappingSpecsApiV1ObjectifyMappingSpecsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        if (requestParameters['datasetId'] != null) {
            queryParameters['dataset_id'] = requestParameters['datasetId'];
        }

        if (requestParameters['includeInactive'] != null) {
            queryParameters['include_inactive'] = requestParameters['includeInactive'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/mapping-specs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List Mapping Specs
     */
    async listMappingSpecsApiV1ObjectifyMappingSpecsGet(requestParameters: ListMappingSpecsApiV1ObjectifyMappingSpecsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.listMappingSpecsApiV1ObjectifyMappingSpecsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Mapping Specs
     */
    async listMappingSpecsApiV1ObjectifyMappingSpecsGet_4Raw(requestParameters: ListMappingSpecsApiV1ObjectifyMappingSpecsGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        if (requestParameters['datasetId'] != null) {
            queryParameters['dataset_id'] = requestParameters['datasetId'];
        }

        if (requestParameters['includeInactive'] != null) {
            queryParameters['include_inactive'] = requestParameters['includeInactive'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/mapping-specs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List Mapping Specs
     */
    async listMappingSpecsApiV1ObjectifyMappingSpecsGet_4(requestParameters: ListMappingSpecsApiV1ObjectifyMappingSpecsGet0Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.listMappingSpecsApiV1ObjectifyMappingSpecsGet_4Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Executes objectify for one specific dataset with explicit mapping spec control.
     * Run objectify for a single dataset
     */
    async runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostRaw(requestParameters: RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost().'
            );
        }

        if (requestParameters['triggerObjectifyRequest'] == null) {
            throw new runtime.RequiredError(
                'triggerObjectifyRequest',
                'Required parameter "triggerObjectifyRequest" was null or undefined when calling runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/datasets/{dataset_id}/run`.replace(`{${"dataset_id"}}`, encodeURIComponent(String(requestParameters['datasetId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriggerObjectifyRequestToJSON(requestParameters['triggerObjectifyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Executes objectify for one specific dataset with explicit mapping spec control.
     * Run objectify for a single dataset
     */
    async runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost(requestParameters: RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Executes objectify for one specific dataset with explicit mapping spec control.
     * Run objectify for a single dataset
     */
    async runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost_5Raw(requestParameters: RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost_5().'
            );
        }

        if (requestParameters['triggerObjectifyRequest'] == null) {
            throw new runtime.RequiredError(
                'triggerObjectifyRequest',
                'Required parameter "triggerObjectifyRequest" was null or undefined when calling runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost_5().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/datasets/{dataset_id}/run`.replace(`{${"dataset_id"}}`, encodeURIComponent(String(requestParameters['datasetId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriggerObjectifyRequestToJSON(requestParameters['triggerObjectifyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Executes objectify for one specific dataset with explicit mapping spec control.
     * Run objectify for a single dataset
     */
    async runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost_5(requestParameters: RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.runObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost_5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resolves dependency graph and fans out objectify jobs for all specified classes. Use this for full batch processing.
     * Orchestrate objectify across multiple ontology classes (DAG)
     */
    async runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostRaw(requestParameters: RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['dbName'] == null) {
            throw new runtime.RequiredError(
                'dbName',
                'Required parameter "dbName" was null or undefined when calling runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost().'
            );
        }

        if (requestParameters['runObjectifyDAGRequest'] == null) {
            throw new runtime.RequiredError(
                'runObjectifyDAGRequest',
                'Required parameter "runObjectifyDAGRequest" was null or undefined when calling runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/databases/{db_name}/run-dag`.replace(`{${"db_name"}}`, encodeURIComponent(String(requestParameters['dbName']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunObjectifyDAGRequestToJSON(requestParameters['runObjectifyDAGRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Resolves dependency graph and fans out objectify jobs for all specified classes. Use this for full batch processing.
     * Orchestrate objectify across multiple ontology classes (DAG)
     */
    async runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost(requestParameters: RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resolves dependency graph and fans out objectify jobs for all specified classes. Use this for full batch processing.
     * Orchestrate objectify across multiple ontology classes (DAG)
     */
    async runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost_6Raw(requestParameters: RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['dbName'] == null) {
            throw new runtime.RequiredError(
                'dbName',
                'Required parameter "dbName" was null or undefined when calling runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost_6().'
            );
        }

        if (requestParameters['runObjectifyDAGRequest'] == null) {
            throw new runtime.RequiredError(
                'runObjectifyDAGRequest',
                'Required parameter "runObjectifyDAGRequest" was null or undefined when calling runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost_6().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/databases/{db_name}/run-dag`.replace(`{${"db_name"}}`, encodeURIComponent(String(requestParameters['dbName']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunObjectifyDAGRequestToJSON(requestParameters['runObjectifyDAGRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Resolves dependency graph and fans out objectify jobs for all specified classes. Use this for full batch processing.
     * Orchestrate objectify across multiple ontology classes (DAG)
     */
    async runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost_6(requestParameters: RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.runObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost_6Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Trigger objectify in incremental mode, processing only rows changed since last run.
     * Trigger incremental objectify
     */
    async triggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostRaw(requestParameters: TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['mappingSpecId'] == null) {
            throw new runtime.RequiredError(
                'mappingSpecId',
                'Required parameter "mappingSpecId" was null or undefined when calling triggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/mapping-specs/{mapping_spec_id}/trigger-incremental`.replace(`{${"mapping_spec_id"}}`, encodeURIComponent(String(requestParameters['mappingSpecId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriggerIncrementalRequestToJSON(requestParameters['triggerIncrementalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Trigger objectify in incremental mode, processing only rows changed since last run.
     * Trigger incremental objectify
     */
    async triggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost(requestParameters: TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.triggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Trigger objectify in incremental mode, processing only rows changed since last run.
     * Trigger incremental objectify
     */
    async triggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost_7Raw(requestParameters: TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['mappingSpecId'] == null) {
            throw new runtime.RequiredError(
                'mappingSpecId',
                'Required parameter "mappingSpecId" was null or undefined when calling triggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost_7().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        const response = await this.request({
            path: `/api/v1/objectify/mapping-specs/{mapping_spec_id}/trigger-incremental`.replace(`{${"mapping_spec_id"}}`, encodeURIComponent(String(requestParameters['mappingSpecId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriggerIncrementalRequestToJSON(requestParameters['triggerIncrementalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Trigger objectify in incremental mode, processing only rows changed since last run.
     * Trigger incremental objectify
     */
    async triggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost_7(requestParameters: TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.triggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost_7Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateMappingSpecApiV1ObjectifyMappingSpecsPostLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type CreateMappingSpecApiV1ObjectifyMappingSpecsPostLangEnum = typeof CreateMappingSpecApiV1ObjectifyMappingSpecsPostLangEnum[keyof typeof CreateMappingSpecApiV1ObjectifyMappingSpecsPostLangEnum];
/**
 * @export
 */
export const CreateMappingSpecApiV1ObjectifyMappingSpecsPost0LangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type CreateMappingSpecApiV1ObjectifyMappingSpecsPost0LangEnum = typeof CreateMappingSpecApiV1ObjectifyMappingSpecsPost0LangEnum[keyof typeof CreateMappingSpecApiV1ObjectifyMappingSpecsPost0LangEnum];
/**
 * @export
 */
export const DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostLangEnum = typeof DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostLangEnum[keyof typeof DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPostLangEnum];
/**
 * @export
 */
export const DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost0LangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost0LangEnum = typeof DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost0LangEnum[keyof typeof DetectRelationshipsApiV1ObjectifyDatabasesDbNameDatasetsDatasetIdDetectRelationshipsPost0LangEnum];
/**
 * @export
 */
export const GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetLangEnum = typeof GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetLangEnum[keyof typeof GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGetLangEnum];
/**
 * @export
 */
export const GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet0LangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet0LangEnum = typeof GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet0LangEnum[keyof typeof GetMappingSpecWatermarkApiV1ObjectifyMappingSpecsMappingSpecIdWatermarkGet0LangEnum];
/**
 * @export
 */
export const ListMappingSpecsApiV1ObjectifyMappingSpecsGetLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type ListMappingSpecsApiV1ObjectifyMappingSpecsGetLangEnum = typeof ListMappingSpecsApiV1ObjectifyMappingSpecsGetLangEnum[keyof typeof ListMappingSpecsApiV1ObjectifyMappingSpecsGetLangEnum];
/**
 * @export
 */
export const ListMappingSpecsApiV1ObjectifyMappingSpecsGet0LangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type ListMappingSpecsApiV1ObjectifyMappingSpecsGet0LangEnum = typeof ListMappingSpecsApiV1ObjectifyMappingSpecsGet0LangEnum[keyof typeof ListMappingSpecsApiV1ObjectifyMappingSpecsGet0LangEnum];
/**
 * @export
 */
export const RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostLangEnum = typeof RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostLangEnum[keyof typeof RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPostLangEnum];
/**
 * @export
 */
export const RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost0LangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost0LangEnum = typeof RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost0LangEnum[keyof typeof RunObjectifyApiV1ObjectifyDatasetsDatasetIdRunPost0LangEnum];
/**
 * @export
 */
export const RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostLangEnum = typeof RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostLangEnum[keyof typeof RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPostLangEnum];
/**
 * @export
 */
export const RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost0LangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost0LangEnum = typeof RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost0LangEnum[keyof typeof RunObjectifyDagApiV1ObjectifyDatabasesDbNameRunDagPost0LangEnum];
/**
 * @export
 */
export const TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostLangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostLangEnum = typeof TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostLangEnum[keyof typeof TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPostLangEnum];
/**
 * @export
 */
export const TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost0LangEnum = {
    En: 'en',
    Ko: 'ko'
} as const;
export type TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost0LangEnum = typeof TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost0LangEnum[keyof typeof TriggerIncrementalObjectifyApiV1ObjectifyMappingSpecsMappingSpecIdTriggerIncrementalPost0LangEnum];
