/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface AccessPolicyRequest
 */
export interface AccessPolicyRequest {
    /**
     * 
     * @type {string}
     * @memberof AccessPolicyRequest
     */
    dbName: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AccessPolicyRequest
     */
    policy?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof AccessPolicyRequest
     */
    scope?: string;
    /**
     * 
     * @type {Status}
     * @memberof AccessPolicyRequest
     */
    status?: Status;
    /**
     * 
     * @type {string}
     * @memberof AccessPolicyRequest
     */
    subjectId: string;
    /**
     * 
     * @type {string}
     * @memberof AccessPolicyRequest
     */
    subjectType: string;
}

/**
 * Check if a given object implements the AccessPolicyRequest interface.
 */
export function instanceOfAccessPolicyRequest(value: object): value is AccessPolicyRequest {
    if (!('dbName' in value) || value['dbName'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('subjectType' in value) || value['subjectType'] === undefined) return false;
    return true;
}

export function AccessPolicyRequestFromJSON(json: any): AccessPolicyRequest {
    return AccessPolicyRequestFromJSONTyped(json, false);
}

export function AccessPolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessPolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'dbName': json['db_name'],
        'policy': json['policy'] == null ? undefined : json['policy'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
        'subjectId': json['subject_id'],
        'subjectType': json['subject_type'],
    };
}

export function AccessPolicyRequestToJSON(json: any): AccessPolicyRequest {
    return AccessPolicyRequestToJSONTyped(json, false);
}

export function AccessPolicyRequestToJSONTyped(value?: AccessPolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'db_name': value['dbName'],
        'policy': value['policy'],
        'scope': value['scope'],
        'status': StatusToJSON(value['status']),
        'subject_id': value['subjectId'],
        'subject_type': value['subjectType'],
    };
}

