/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentSessionCIResultIngestRequest
 */
export interface AgentSessionCIResultIngestRequest {
    /**
     * 
     * @type {Array<any>}
     * @memberof AgentSessionCIResultIngestRequest
     */
    checks?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    ciResultId?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    detailsUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    jobId?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    planId?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    provider?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AgentSessionCIResultIngestRequest
     */
    raw?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    runId?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentSessionCIResultIngestRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the AgentSessionCIResultIngestRequest interface.
 */
export function instanceOfAgentSessionCIResultIngestRequest(value: object): value is AgentSessionCIResultIngestRequest {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function AgentSessionCIResultIngestRequestFromJSON(json: any): AgentSessionCIResultIngestRequest {
    return AgentSessionCIResultIngestRequestFromJSONTyped(json, false);
}

export function AgentSessionCIResultIngestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentSessionCIResultIngestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'checks': json['checks'] == null ? undefined : json['checks'],
        'ciResultId': json['ci_result_id'] == null ? undefined : json['ci_result_id'],
        'detailsUrl': json['details_url'] == null ? undefined : json['details_url'],
        'jobId': json['job_id'] == null ? undefined : json['job_id'],
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'raw': json['raw'] == null ? undefined : json['raw'],
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'sessionId': json['session_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'tenantId': json['tenant_id'],
    };
}

export function AgentSessionCIResultIngestRequestToJSON(json: any): AgentSessionCIResultIngestRequest {
    return AgentSessionCIResultIngestRequestToJSONTyped(json, false);
}

export function AgentSessionCIResultIngestRequestToJSONTyped(value?: AgentSessionCIResultIngestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checks': value['checks'],
        'ci_result_id': value['ciResultId'],
        'details_url': value['detailsUrl'],
        'job_id': value['jobId'],
        'plan_id': value['planId'],
        'provider': value['provider'],
        'raw': value['raw'],
        'run_id': value['runId'],
        'session_id': value['sessionId'],
        'status': value['status'],
        'summary': value['summary'],
        'tenant_id': value['tenantId'],
    };
}

