/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AIIntentType } from './AIIntentType';
import {
    AIIntentTypeFromJSON,
    AIIntentTypeFromJSONTyped,
    AIIntentTypeToJSON,
    AIIntentTypeToJSONTyped,
} from './AIIntentType';
import type { AIIntentRoute } from './AIIntentRoute';
import {
    AIIntentRouteFromJSON,
    AIIntentRouteFromJSONTyped,
    AIIntentRouteToJSON,
    AIIntentRouteToJSONTyped,
} from './AIIntentRoute';

/**
 * 
 * @export
 * @interface AIIntentResponse
 */
export interface AIIntentResponse {
    /**
     * 
     * @type {string}
     * @memberof AIIntentResponse
     */
    clarifyingQuestion?: string;
    /**
     * 
     * @type {number}
     * @memberof AIIntentResponse
     */
    confidence: number;
    /**
     * 
     * @type {AIIntentType}
     * @memberof AIIntentResponse
     */
    intent: AIIntentType;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AIIntentResponse
     */
    llm?: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof AIIntentResponse
     */
    missingFields?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AIIntentResponse
     */
    reply?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AIIntentResponse
     */
    requiresClarification?: boolean;
    /**
     * 
     * @type {AIIntentRoute}
     * @memberof AIIntentResponse
     */
    route: AIIntentRoute;
}



/**
 * Check if a given object implements the AIIntentResponse interface.
 */
export function instanceOfAIIntentResponse(value: object): value is AIIntentResponse {
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('intent' in value) || value['intent'] === undefined) return false;
    if (!('route' in value) || value['route'] === undefined) return false;
    return true;
}

export function AIIntentResponseFromJSON(json: any): AIIntentResponse {
    return AIIntentResponseFromJSONTyped(json, false);
}

export function AIIntentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AIIntentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'clarifyingQuestion': json['clarifying_question'] == null ? undefined : json['clarifying_question'],
        'confidence': json['confidence'],
        'intent': AIIntentTypeFromJSON(json['intent']),
        'llm': json['llm'] == null ? undefined : json['llm'],
        'missingFields': json['missing_fields'] == null ? undefined : json['missing_fields'],
        'reply': json['reply'] == null ? undefined : json['reply'],
        'requiresClarification': json['requires_clarification'] == null ? undefined : json['requires_clarification'],
        'route': AIIntentRouteFromJSON(json['route']),
    };
}

export function AIIntentResponseToJSON(json: any): AIIntentResponse {
    return AIIntentResponseToJSONTyped(json, false);
}

export function AIIntentResponseToJSONTyped(value?: AIIntentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clarifying_question': value['clarifyingQuestion'],
        'confidence': value['confidence'],
        'intent': AIIntentTypeToJSON(value['intent']),
        'llm': value['llm'],
        'missing_fields': value['missingFields'],
        'reply': value['reply'],
        'requires_clarification': value['requiresClarification'],
        'route': AIIntentRouteToJSON(value['route']),
    };
}

