/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AIQueryMode } from './AIQueryMode';
import {
    AIQueryModeFromJSON,
    AIQueryModeFromJSONTyped,
    AIQueryModeToJSON,
    AIQueryModeToJSONTyped,
} from './AIQueryMode';

/**
 * 
 * @export
 * @interface AIQueryRequest
 */
export interface AIQueryRequest {
    /**
     * Branch for graph queries (default: main)
     * @type {string}
     * @memberof AIQueryRequest
     */
    branch?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AIQueryRequest
     */
    includeDocuments?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AIQueryRequest
     */
    includeProvenance?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AIQueryRequest
     */
    limit?: number;
    /**
     * 
     * @type {AIQueryMode}
     * @memberof AIQueryRequest
     */
    mode?: AIQueryMode;
    /**
     * 
     * @type {string}
     * @memberof AIQueryRequest
     */
    question: string;
    /**
     * 
     * @type {string}
     * @memberof AIQueryRequest
     */
    sessionId?: string;
}



/**
 * Check if a given object implements the AIQueryRequest interface.
 */
export function instanceOfAIQueryRequest(value: object): value is AIQueryRequest {
    if (!('question' in value) || value['question'] === undefined) return false;
    return true;
}

export function AIQueryRequestFromJSON(json: any): AIQueryRequest {
    return AIQueryRequestFromJSONTyped(json, false);
}

export function AIQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AIQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'] == null ? undefined : json['branch'],
        'includeDocuments': json['include_documents'] == null ? undefined : json['include_documents'],
        'includeProvenance': json['include_provenance'] == null ? undefined : json['include_provenance'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'mode': json['mode'] == null ? undefined : AIQueryModeFromJSON(json['mode']),
        'question': json['question'],
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
    };
}

export function AIQueryRequestToJSON(json: any): AIQueryRequest {
    return AIQueryRequestToJSONTyped(json, false);
}

export function AIQueryRequestToJSONTyped(value?: AIQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch': value['branch'],
        'include_documents': value['includeDocuments'],
        'include_provenance': value['includeProvenance'],
        'limit': value['limit'],
        'mode': AIQueryModeToJSON(value['mode']),
        'question': value['question'],
        'session_id': value['sessionId'],
    };
}

