/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchApplyActionRequestOptionsV2 } from './BatchApplyActionRequestOptionsV2';
import {
    BatchApplyActionRequestOptionsV2FromJSON,
    BatchApplyActionRequestOptionsV2FromJSONTyped,
    BatchApplyActionRequestOptionsV2ToJSON,
    BatchApplyActionRequestOptionsV2ToJSONTyped,
} from './BatchApplyActionRequestOptionsV2';
import type { BatchApplyActionRequestItemV2 } from './BatchApplyActionRequestItemV2';
import {
    BatchApplyActionRequestItemV2FromJSON,
    BatchApplyActionRequestItemV2FromJSONTyped,
    BatchApplyActionRequestItemV2ToJSON,
    BatchApplyActionRequestItemV2ToJSONTyped,
} from './BatchApplyActionRequestItemV2';

/**
 * 
 * @export
 * @interface BatchApplyActionRequestV2
 */
export interface BatchApplyActionRequestV2 {
    /**
     * 
     * @type {BatchApplyActionRequestOptionsV2}
     * @memberof BatchApplyActionRequestV2
     */
    options?: BatchApplyActionRequestOptionsV2;
    /**
     * 
     * @type {Array<BatchApplyActionRequestItemV2>}
     * @memberof BatchApplyActionRequestV2
     */
    requests?: Array<BatchApplyActionRequestItemV2>;
}

/**
 * Check if a given object implements the BatchApplyActionRequestV2 interface.
 */
export function instanceOfBatchApplyActionRequestV2(value: object): value is BatchApplyActionRequestV2 {
    return true;
}

export function BatchApplyActionRequestV2FromJSON(json: any): BatchApplyActionRequestV2 {
    return BatchApplyActionRequestV2FromJSONTyped(json, false);
}

export function BatchApplyActionRequestV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchApplyActionRequestV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'options': json['options'] == null ? undefined : BatchApplyActionRequestOptionsV2FromJSON(json['options']),
        'requests': json['requests'] == null ? undefined : ((json['requests'] as Array<any>).map(BatchApplyActionRequestItemV2FromJSON)),
    };
}

export function BatchApplyActionRequestV2ToJSON(json: any): BatchApplyActionRequestV2 {
    return BatchApplyActionRequestV2ToJSONTyped(json, false);
}

export function BatchApplyActionRequestV2ToJSONTyped(value?: BatchApplyActionRequestV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'options': BatchApplyActionRequestOptionsV2ToJSON(value['options']),
        'requests': value['requests'] == null ? undefined : ((value['requests'] as Array<any>).map(BatchApplyActionRequestItemV2ToJSON)),
    };
}

