/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommandStatus } from './CommandStatus';
import {
    CommandStatusFromJSON,
    CommandStatusFromJSONTyped,
    CommandStatusToJSON,
    CommandStatusToJSONTyped,
} from './CommandStatus';

/**
 * 명령 실행 결과
 * @export
 * @interface CommandResult
 */
export interface CommandResult {
    /**
     * 명령 ID
     * @type {string}
     * @memberof CommandResult
     */
    commandId: string;
    /**
     * 
     * @type {Date}
     * @memberof CommandResult
     */
    completedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CommandResult
     */
    error?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CommandResult
     */
    result?: { [key: string]: any; };
    /**
     * 재시도 횟수
     * @type {number}
     * @memberof CommandResult
     */
    retryCount?: number;
    /**
     * 실행 상태
     * @type {CommandStatus}
     * @memberof CommandResult
     */
    status: CommandStatus;
}



/**
 * Check if a given object implements the CommandResult interface.
 */
export function instanceOfCommandResult(value: object): value is CommandResult {
    if (!('commandId' in value) || value['commandId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CommandResultFromJSON(json: any): CommandResult {
    return CommandResultFromJSONTyped(json, false);
}

export function CommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandResult {
    if (json == null) {
        return json;
    }
    return {
        
        'commandId': json['command_id'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : json['result'],
        'retryCount': json['retry_count'] == null ? undefined : json['retry_count'],
        'status': CommandStatusFromJSON(json['status']),
    };
}

export function CommandResultToJSON(json: any): CommandResult {
    return CommandResultToJSONTyped(json, false);
}

export function CommandResultToJSONTyped(value?: CommandResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command_id': value['commandId'],
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt']).toISOString()),
        'error': value['error'],
        'result': value['result'],
        'retry_count': value['retryCount'],
        'status': CommandStatusToJSON(value['status']),
    };
}

