/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatabaseAccessEntryRequest
 */
export interface DatabaseAccessEntryRequest {
    /**
     * Principal identifier (e.g., JWT subject)
     * @type {string}
     * @memberof DatabaseAccessEntryRequest
     */
    principalId: string;
    /**
     * 
     * @type {string}
     * @memberof DatabaseAccessEntryRequest
     */
    principalName?: string;
    /**
     * Principal type (e.g., user, service)
     * @type {string}
     * @memberof DatabaseAccessEntryRequest
     */
    principalType?: string;
    /**
     * Database role (Owner/Editor/Viewer/DomainModeler/DataEngineer/Security)
     * @type {string}
     * @memberof DatabaseAccessEntryRequest
     */
    role: string;
}

/**
 * Check if a given object implements the DatabaseAccessEntryRequest interface.
 */
export function instanceOfDatabaseAccessEntryRequest(value: object): value is DatabaseAccessEntryRequest {
    if (!('principalId' in value) || value['principalId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function DatabaseAccessEntryRequestFromJSON(json: any): DatabaseAccessEntryRequest {
    return DatabaseAccessEntryRequestFromJSONTyped(json, false);
}

export function DatabaseAccessEntryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatabaseAccessEntryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'principalId': json['principal_id'],
        'principalName': json['principal_name'] == null ? undefined : json['principal_name'],
        'principalType': json['principal_type'] == null ? undefined : json['principal_type'],
        'role': json['role'],
    };
}

export function DatabaseAccessEntryRequestToJSON(json: any): DatabaseAccessEntryRequest {
    return DatabaseAccessEntryRequestToJSONTyped(json, false);
}

export function DatabaseAccessEntryRequestToJSONTyped(value?: DatabaseAccessEntryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'principal_id': value['principalId'],
        'principal_name': value['principalName'],
        'principal_type': value['principalType'],
        'role': value['role'],
    };
}

