/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatasetListQuery
 */
export interface DatasetListQuery {
    /**
     * 
     * @type {number}
     * @memberof DatasetListQuery
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof DatasetListQuery
     */
    nameContains?: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetListQuery
     */
    sourceType?: string;
}

/**
 * Check if a given object implements the DatasetListQuery interface.
 */
export function instanceOfDatasetListQuery(value: object): value is DatasetListQuery {
    return true;
}

export function DatasetListQueryFromJSON(json: any): DatasetListQuery {
    return DatasetListQueryFromJSONTyped(json, false);
}

export function DatasetListQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetListQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'nameContains': json['name_contains'] == null ? undefined : json['name_contains'],
        'sourceType': json['source_type'] == null ? undefined : json['source_type'],
    };
}

export function DatasetListQueryToJSON(json: any): DatasetListQuery {
    return DatasetListQueryToJSONTyped(json, false);
}

export function DatasetListQueryToJSONTyped(value?: DatasetListQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'name_contains': value['nameContains'],
        'source_type': value['sourceType'],
    };
}

