/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Resource description
 * @export
 * @interface Description
 */
export interface Description {
}

/**
 * Check if a given object implements the Description interface.
 */
export function instanceOfDescription(value: object): value is Description {
    return true;
}

export function DescriptionFromJSON(json: any): Description {
    return DescriptionFromJSONTyped(json, false);
}

export function DescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Description {
    return json;
}

export function DescriptionToJSON(json: any): Description {
    return DescriptionToJSONTyped(json, false);
}

export function DescriptionToJSONTyped(value?: Description | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

