/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface GatePolicyRequest
 */
export interface GatePolicyRequest {
    /**
     * 
     * @type {string}
     * @memberof GatePolicyRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GatePolicyRequest
     */
    name: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GatePolicyRequest
     */
    rules?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof GatePolicyRequest
     */
    scope: string;
    /**
     * 
     * @type {Status}
     * @memberof GatePolicyRequest
     */
    status?: Status;
}

/**
 * Check if a given object implements the GatePolicyRequest interface.
 */
export function instanceOfGatePolicyRequest(value: object): value is GatePolicyRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function GatePolicyRequestFromJSON(json: any): GatePolicyRequest {
    return GatePolicyRequestFromJSONTyped(json, false);
}

export function GatePolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatePolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'rules': json['rules'] == null ? undefined : json['rules'],
        'scope': json['scope'],
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
    };
}

export function GatePolicyRequestToJSON(json: any): GatePolicyRequest {
    return GatePolicyRequestToJSONTyped(json, false);
}

export function GatePolicyRequestToJSONTyped(value?: GatePolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'rules': value['rules'],
        'scope': value['scope'],
        'status': StatusToJSON(value['status']),
    };
}

