/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GraphHop } from './GraphHop';
import {
    GraphHopFromJSON,
    GraphHopFromJSONTyped,
    GraphHopToJSON,
    GraphHopToJSONTyped,
} from './GraphHop';

/**
 * Request model for multi-hop graph queries.
 * @export
 * @interface GraphQueryRequest
 */
export interface GraphQueryRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GraphQueryRequest
     */
    filters?: { [key: string]: any; };
    /**
     * 
     * @type {Array<GraphHop>}
     * @memberof GraphQueryRequest
     */
    hops: Array<GraphHop>;
    /**
     * 
     * @type {boolean}
     * @memberof GraphQueryRequest
     */
    includeAudit?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GraphQueryRequest
     */
    includeDocuments?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GraphQueryRequest
     */
    includePaths?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GraphQueryRequest
     */
    includeProvenance?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GraphQueryRequest
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof GraphQueryRequest
     */
    maxEdges?: number;
    /**
     * 
     * @type {number}
     * @memberof GraphQueryRequest
     */
    maxNodes?: number;
    /**
     * 
     * @type {number}
     * @memberof GraphQueryRequest
     */
    maxPaths?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GraphQueryRequest
     */
    noCycles?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GraphQueryRequest
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof GraphQueryRequest
     */
    pathDepthLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof GraphQueryRequest
     */
    startClass: string;
}

/**
 * Check if a given object implements the GraphQueryRequest interface.
 */
export function instanceOfGraphQueryRequest(value: object): value is GraphQueryRequest {
    if (!('hops' in value) || value['hops'] === undefined) return false;
    if (!('startClass' in value) || value['startClass'] === undefined) return false;
    return true;
}

export function GraphQueryRequestFromJSON(json: any): GraphQueryRequest {
    return GraphQueryRequestFromJSONTyped(json, false);
}

export function GraphQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filters': json['filters'] == null ? undefined : json['filters'],
        'hops': ((json['hops'] as Array<any>).map(GraphHopFromJSON)),
        'includeAudit': json['include_audit'] == null ? undefined : json['include_audit'],
        'includeDocuments': json['include_documents'] == null ? undefined : json['include_documents'],
        'includePaths': json['include_paths'] == null ? undefined : json['include_paths'],
        'includeProvenance': json['include_provenance'] == null ? undefined : json['include_provenance'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'maxEdges': json['max_edges'] == null ? undefined : json['max_edges'],
        'maxNodes': json['max_nodes'] == null ? undefined : json['max_nodes'],
        'maxPaths': json['max_paths'] == null ? undefined : json['max_paths'],
        'noCycles': json['no_cycles'] == null ? undefined : json['no_cycles'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'pathDepthLimit': json['path_depth_limit'] == null ? undefined : json['path_depth_limit'],
        'startClass': json['start_class'],
    };
}

export function GraphQueryRequestToJSON(json: any): GraphQueryRequest {
    return GraphQueryRequestToJSONTyped(json, false);
}

export function GraphQueryRequestToJSONTyped(value?: GraphQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filters': value['filters'],
        'hops': ((value['hops'] as Array<any>).map(GraphHopToJSON)),
        'include_audit': value['includeAudit'],
        'include_documents': value['includeDocuments'],
        'include_paths': value['includePaths'],
        'include_provenance': value['includeProvenance'],
        'limit': value['limit'],
        'max_edges': value['maxEdges'],
        'max_nodes': value['maxNodes'],
        'max_paths': value['maxPaths'],
        'no_cycles': value['noCycles'],
        'offset': value['offset'],
        'path_depth_limit': value['pathDepthLimit'],
        'start_class': value['startClass'],
    };
}

