/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Graph node with ES document reference.
 * @export
 * @interface GraphNode
 */
export interface GraphNode {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GraphNode
     */
    data?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    dataStatus: string;
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    dbName: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GraphNode
     */
    display?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    esDocId: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GraphNode
     */
    esRef: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GraphNode
     */
    indexStatus?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GraphNode
     */
    provenance?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    type: string;
}

/**
 * Check if a given object implements the GraphNode interface.
 */
export function instanceOfGraphNode(value: object): value is GraphNode {
    if (!('dataStatus' in value) || value['dataStatus'] === undefined) return false;
    if (!('dbName' in value) || value['dbName'] === undefined) return false;
    if (!('esDocId' in value) || value['esDocId'] === undefined) return false;
    if (!('esRef' in value) || value['esRef'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function GraphNodeFromJSON(json: any): GraphNode {
    return GraphNodeFromJSONTyped(json, false);
}

export function GraphNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphNode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'dataStatus': json['data_status'],
        'dbName': json['db_name'],
        'display': json['display'] == null ? undefined : json['display'],
        'esDocId': json['es_doc_id'],
        'esRef': json['es_ref'],
        'id': json['id'],
        'indexStatus': json['index_status'] == null ? undefined : json['index_status'],
        'provenance': json['provenance'] == null ? undefined : json['provenance'],
        'type': json['type'],
    };
}

export function GraphNodeToJSON(json: any): GraphNode {
    return GraphNodeToJSONTyped(json, false);
}

export function GraphNodeToJSONTyped(value?: GraphNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'data_status': value['dataStatus'],
        'db_name': value['dbName'],
        'display': value['display'],
        'es_doc_id': value['esDocId'],
        'es_ref': value['esRef'],
        'id': value['id'],
        'index_status': value['indexStatus'],
        'provenance': value['provenance'],
        'type': value['type'],
    };
}

