/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Upsert request for lakeFS credentials stored in Postgres (encrypted).
 * @export
 * @interface LakeFSCredentialsUpsertRequest
 */
export interface LakeFSCredentialsUpsertRequest {
    /**
     * lakeFS access key id
     * @type {string}
     * @memberof LakeFSCredentialsUpsertRequest
     */
    accessKeyId: string;
    /**
     * User ID or service name
     * @type {string}
     * @memberof LakeFSCredentialsUpsertRequest
     */
    principalId: string;
    /**
     * Principal type (user|service)
     * @type {string}
     * @memberof LakeFSCredentialsUpsertRequest
     */
    principalType: LakeFSCredentialsUpsertRequestPrincipalTypeEnum;
    /**
     * lakeFS secret access key
     * @type {string}
     * @memberof LakeFSCredentialsUpsertRequest
     */
    secretAccessKey: string;
}


/**
 * @export
 */
export const LakeFSCredentialsUpsertRequestPrincipalTypeEnum = {
    User: 'user',
    Service: 'service'
} as const;
export type LakeFSCredentialsUpsertRequestPrincipalTypeEnum = typeof LakeFSCredentialsUpsertRequestPrincipalTypeEnum[keyof typeof LakeFSCredentialsUpsertRequestPrincipalTypeEnum];


/**
 * Check if a given object implements the LakeFSCredentialsUpsertRequest interface.
 */
export function instanceOfLakeFSCredentialsUpsertRequest(value: object): value is LakeFSCredentialsUpsertRequest {
    if (!('accessKeyId' in value) || value['accessKeyId'] === undefined) return false;
    if (!('principalId' in value) || value['principalId'] === undefined) return false;
    if (!('principalType' in value) || value['principalType'] === undefined) return false;
    if (!('secretAccessKey' in value) || value['secretAccessKey'] === undefined) return false;
    return true;
}

export function LakeFSCredentialsUpsertRequestFromJSON(json: any): LakeFSCredentialsUpsertRequest {
    return LakeFSCredentialsUpsertRequestFromJSONTyped(json, false);
}

export function LakeFSCredentialsUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LakeFSCredentialsUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKeyId': json['access_key_id'],
        'principalId': json['principal_id'],
        'principalType': json['principal_type'],
        'secretAccessKey': json['secret_access_key'],
    };
}

export function LakeFSCredentialsUpsertRequestToJSON(json: any): LakeFSCredentialsUpsertRequest {
    return LakeFSCredentialsUpsertRequestToJSONTyped(json, false);
}

export function LakeFSCredentialsUpsertRequestToJSONTyped(value?: LakeFSCredentialsUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_key_id': value['accessKeyId'],
        'principal_id': value['principalId'],
        'principal_type': value['principalType'],
        'secret_access_key': value['secretAccessKey'],
    };
}

