/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MappingSpecField
 */
export interface MappingSpecField {
    /**
     * 
     * @type {string}
     * @memberof MappingSpecField
     */
    sourceField: string;
    /**
     * 
     * @type {string}
     * @memberof MappingSpecField
     */
    targetField: string;
}

/**
 * Check if a given object implements the MappingSpecField interface.
 */
export function instanceOfMappingSpecField(value: object): value is MappingSpecField {
    if (!('sourceField' in value) || value['sourceField'] === undefined) return false;
    if (!('targetField' in value) || value['targetField'] === undefined) return false;
    return true;
}

export function MappingSpecFieldFromJSON(json: any): MappingSpecField {
    return MappingSpecFieldFromJSONTyped(json, false);
}

export function MappingSpecFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): MappingSpecField {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceField': json['source_field'],
        'targetField': json['target_field'],
    };
}

export function MappingSpecFieldToJSON(json: any): MappingSpecField {
    return MappingSpecFieldToJSONTyped(json, false);
}

export function MappingSpecFieldToJSONTyped(value?: MappingSpecField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_field': value['sourceField'],
        'target_field': value['targetField'],
    };
}

