/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectTypeContractUpdateRequestV2
 */
export interface ObjectTypeContractUpdateRequestV2 {
    /**
     * 
     * @type {string}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    backingDatasetId?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    backingDatasourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    backingDatasourceVersionId?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    backingSource?: { [key: string]: any; };
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    backingSources?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {string}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    datasetVersionId?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    mappingSpecId?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    mappingSpecVersion?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    migration?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    pkSpec?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    primaryKey?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    schemaHash?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectTypeContractUpdateRequestV2
     */
    titleProperty?: string;
}

/**
 * Check if a given object implements the ObjectTypeContractUpdateRequestV2 interface.
 */
export function instanceOfObjectTypeContractUpdateRequestV2(value: object): value is ObjectTypeContractUpdateRequestV2 {
    return true;
}

export function ObjectTypeContractUpdateRequestV2FromJSON(json: any): ObjectTypeContractUpdateRequestV2 {
    return ObjectTypeContractUpdateRequestV2FromJSONTyped(json, false);
}

export function ObjectTypeContractUpdateRequestV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectTypeContractUpdateRequestV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'backingDatasetId': json['backingDatasetId'] == null ? undefined : json['backingDatasetId'],
        'backingDatasourceId': json['backingDatasourceId'] == null ? undefined : json['backingDatasourceId'],
        'backingDatasourceVersionId': json['backingDatasourceVersionId'] == null ? undefined : json['backingDatasourceVersionId'],
        'backingSource': json['backingSource'] == null ? undefined : json['backingSource'],
        'backingSources': json['backingSources'] == null ? undefined : json['backingSources'],
        'datasetVersionId': json['datasetVersionId'] == null ? undefined : json['datasetVersionId'],
        'mappingSpecId': json['mappingSpecId'] == null ? undefined : json['mappingSpecId'],
        'mappingSpecVersion': json['mappingSpecVersion'] == null ? undefined : json['mappingSpecVersion'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'migration': json['migration'] == null ? undefined : json['migration'],
        'pkSpec': json['pkSpec'] == null ? undefined : json['pkSpec'],
        'primaryKey': json['primaryKey'] == null ? undefined : json['primaryKey'],
        'schemaHash': json['schemaHash'] == null ? undefined : json['schemaHash'],
        'status': json['status'] == null ? undefined : json['status'],
        'titleProperty': json['titleProperty'] == null ? undefined : json['titleProperty'],
    };
}

export function ObjectTypeContractUpdateRequestV2ToJSON(json: any): ObjectTypeContractUpdateRequestV2 {
    return ObjectTypeContractUpdateRequestV2ToJSONTyped(json, false);
}

export function ObjectTypeContractUpdateRequestV2ToJSONTyped(value?: ObjectTypeContractUpdateRequestV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'backingDatasetId': value['backingDatasetId'],
        'backingDatasourceId': value['backingDatasourceId'],
        'backingDatasourceVersionId': value['backingDatasourceVersionId'],
        'backingSource': value['backingSource'],
        'backingSources': value['backingSources'],
        'datasetVersionId': value['datasetVersionId'],
        'mappingSpecId': value['mappingSpecId'],
        'mappingSpecVersion': value['mappingSpecVersion'],
        'metadata': value['metadata'],
        'migration': value['migration'],
        'pkSpec': value['pkSpec'],
        'primaryKey': value['primaryKey'],
        'schemaHash': value['schemaHash'],
        'status': value['status'],
        'titleProperty': value['titleProperty'],
    };
}

