/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryFilter } from './QueryFilter';
import {
    QueryFilterFromJSON,
    QueryFilterFromJSONTyped,
    QueryFilterToJSON,
    QueryFilterToJSONTyped,
} from './QueryFilter';

/**
 * Query input model
 * @export
 * @interface QueryInput
 */
export interface QueryInput {
    /**
     * 
     * @type {string}
     * @memberof QueryInput
     */
    classId?: string;
    /**
     * 
     * @type {string}
     * @memberof QueryInput
     */
    classLabel?: string;
    /**
     * Query filters
     * @type {Array<QueryFilter>}
     * @memberof QueryInput
     */
    filters?: Array<QueryFilter>;
    /**
     * 
     * @type {number}
     * @memberof QueryInput
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof QueryInput
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof QueryInput
     */
    orderBy?: string;
    /**
     * 
     * @type {string}
     * @memberof QueryInput
     */
    orderDirection?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryInput
     */
    select?: Array<string>;
}

/**
 * Check if a given object implements the QueryInput interface.
 */
export function instanceOfQueryInput(value: object): value is QueryInput {
    return true;
}

export function QueryInputFromJSON(json: any): QueryInput {
    return QueryInputFromJSONTyped(json, false);
}

export function QueryInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryInput {
    if (json == null) {
        return json;
    }
    return {
        
        'classId': json['class_id'] == null ? undefined : json['class_id'],
        'classLabel': json['class_label'] == null ? undefined : json['class_label'],
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(QueryFilterFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'orderBy': json['order_by'] == null ? undefined : json['order_by'],
        'orderDirection': json['order_direction'] == null ? undefined : json['order_direction'],
        'select': json['select'] == null ? undefined : json['select'],
    };
}

export function QueryInputToJSON(json: any): QueryInput {
    return QueryInputToJSONTyped(json, false);
}

export function QueryInputToJSONTyped(value?: QueryInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'class_id': value['classId'],
        'class_label': value['classLabel'],
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(QueryFilterToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'order_by': value['orderBy'],
        'order_direction': value['orderDirection'],
        'select': value['select'],
    };
}

