/* tslint:disable */
/* eslint-disable */
/**
 * BFF (Backend for Frontend) Service
 * 사용자 친화적인 레이블 기반 온톨로지 관리 서비스
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskStatusResponse } from './TaskStatusResponse';
import {
    TaskStatusResponseFromJSON,
    TaskStatusResponseFromJSONTyped,
    TaskStatusResponseToJSON,
    TaskStatusResponseToJSONTyped,
} from './TaskStatusResponse';

/**
 * Task list response model.
 * @export
 * @interface TaskListResponse
 */
export interface TaskListResponse {
    /**
     * List of tasks
     * @type {Array<TaskStatusResponse>}
     * @memberof TaskListResponse
     */
    tasks: Array<TaskStatusResponse>;
    /**
     * Total number of tasks
     * @type {number}
     * @memberof TaskListResponse
     */
    total: number;
}

/**
 * Check if a given object implements the TaskListResponse interface.
 */
export function instanceOfTaskListResponse(value: object): value is TaskListResponse {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function TaskListResponseFromJSON(json: any): TaskListResponse {
    return TaskListResponseFromJSONTyped(json, false);
}

export function TaskListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TaskStatusResponseFromJSON)),
        'total': json['total'],
    };
}

export function TaskListResponseToJSON(json: any): TaskListResponse {
    return TaskListResponseToJSONTyped(json, false);
}

export function TaskListResponseToJSONTyped(value?: TaskListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(TaskStatusResponseToJSON)),
        'total': value['total'],
    };
}

