"""Formal enum for ontology validation and health issue codes."""

from enum import Enum


class OntologyValidationCode(str, Enum):
    """Issue codes used by OMS ontology validation flows."""

    IFACE_NOT_FOUND = "IFACE_NOT_FOUND"
    IFACE_MISSING_PROPERTY = "IFACE_MISSING_PROPERTY"
    IFACE_PROPERTY_TYPE_MISMATCH = "IFACE_PROPERTY_TYPE_MISMATCH"
    IFACE_MISSING_RELATIONSHIP = "IFACE_MISSING_RELATIONSHIP"
    IFACE_REL_TARGET_MISMATCH = "IFACE_REL_TARGET_MISMATCH"
    RESOURCE_SPEC_INVALID = "RESOURCE_SPEC_INVALID"
    RESOURCE_MISSING_REFERENCE = "RESOURCE_MISSING_REFERENCE"
    RESOURCE_OBJECT_TYPE_CONTRACT_MISSING = "RESOURCE_OBJECT_TYPE_CONTRACT_MISSING"
    VALUE_TYPE_NOT_FOUND = "VALUE_TYPE_NOT_FOUND"
    VALUE_TYPE_BASE_MISMATCH = "VALUE_TYPE_BASE_MISMATCH"
