# coding: utf-8

"""
    BFF (Backend for Frontend) Service

    사용자 친화적인 레이블 기반 온톨로지 관리 서비스

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import Any, Optional
from typing_extensions import Annotated
from spice_harvester_sdk.models.ai_intent_request import AIIntentRequest
from spice_harvester_sdk.models.ai_intent_response import AIIntentResponse
from spice_harvester_sdk.models.ai_query_request import AIQueryRequest
from spice_harvester_sdk.models.ai_query_response import AIQueryResponse

from spice_harvester_sdk.api_client import ApiClient, RequestSerialized
from spice_harvester_sdk.api_response import ApiResponse
from spice_harvester_sdk.rest import RESTResponseType


class AIApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def ai_intent_api_v1_ai_intent_post(
        self,
        ai_intent_request: AIIntentRequest,
        lang: Annotated[Optional[StrictStr], Field(description="Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.")] = None,
        accept_language: Annotated[Optional[StrictStr], Field(description="Preferred output language for UI-facing fields (fallback when ?lang is not provided).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AIIntentResponse:
        """Ai Intent


        :param ai_intent_request: (required)
        :type ai_intent_request: AIIntentRequest
        :param lang: Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.
        :type lang: str
        :param accept_language: Preferred output language for UI-facing fields (fallback when ?lang is not provided).
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._ai_intent_api_v1_ai_intent_post_serialize(
            ai_intent_request=ai_intent_request,
            lang=lang,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AIIntentResponse",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def ai_intent_api_v1_ai_intent_post_with_http_info(
        self,
        ai_intent_request: AIIntentRequest,
        lang: Annotated[Optional[StrictStr], Field(description="Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.")] = None,
        accept_language: Annotated[Optional[StrictStr], Field(description="Preferred output language for UI-facing fields (fallback when ?lang is not provided).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AIIntentResponse]:
        """Ai Intent


        :param ai_intent_request: (required)
        :type ai_intent_request: AIIntentRequest
        :param lang: Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.
        :type lang: str
        :param accept_language: Preferred output language for UI-facing fields (fallback when ?lang is not provided).
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._ai_intent_api_v1_ai_intent_post_serialize(
            ai_intent_request=ai_intent_request,
            lang=lang,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AIIntentResponse",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def ai_intent_api_v1_ai_intent_post_without_preload_content(
        self,
        ai_intent_request: AIIntentRequest,
        lang: Annotated[Optional[StrictStr], Field(description="Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.")] = None,
        accept_language: Annotated[Optional[StrictStr], Field(description="Preferred output language for UI-facing fields (fallback when ?lang is not provided).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Ai Intent


        :param ai_intent_request: (required)
        :type ai_intent_request: AIIntentRequest
        :param lang: Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.
        :type lang: str
        :param accept_language: Preferred output language for UI-facing fields (fallback when ?lang is not provided).
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._ai_intent_api_v1_ai_intent_post_serialize(
            ai_intent_request=ai_intent_request,
            lang=lang,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AIIntentResponse",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _ai_intent_api_v1_ai_intent_post_serialize(
        self,
        ai_intent_request,
        lang,
        accept_language,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if lang is not None:
            
            _query_params.append(('lang', lang))
            
        # process the header parameters
        if accept_language is not None:
            _header_params['Accept-Language'] = accept_language
        # process the form parameters
        # process the body parameter
        if ai_intent_request is not None:
            _body_params = ai_intent_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/ai/intent',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def ai_query_api_v1_ai_query_db_name_post(
        self,
        db_name: StrictStr,
        ai_query_request: AIQueryRequest,
        dry_run: Annotated[Optional[StrictBool], Field(description="When true, return only the query plan without executing (same as translate/query-plan).")] = None,
        lang: Annotated[Optional[StrictStr], Field(description="Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.")] = None,
        accept_language: Annotated[Optional[StrictStr], Field(description="Preferred output language for UI-facing fields (fallback when ?lang is not provided).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AIQueryResponse:
        """Ai Query


        :param db_name: (required)
        :type db_name: str
        :param ai_query_request: (required)
        :type ai_query_request: AIQueryRequest
        :param dry_run: When true, return only the query plan without executing (same as translate/query-plan).
        :type dry_run: bool
        :param lang: Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.
        :type lang: str
        :param accept_language: Preferred output language for UI-facing fields (fallback when ?lang is not provided).
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._ai_query_api_v1_ai_query_db_name_post_serialize(
            db_name=db_name,
            ai_query_request=ai_query_request,
            dry_run=dry_run,
            lang=lang,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AIQueryResponse",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def ai_query_api_v1_ai_query_db_name_post_with_http_info(
        self,
        db_name: StrictStr,
        ai_query_request: AIQueryRequest,
        dry_run: Annotated[Optional[StrictBool], Field(description="When true, return only the query plan without executing (same as translate/query-plan).")] = None,
        lang: Annotated[Optional[StrictStr], Field(description="Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.")] = None,
        accept_language: Annotated[Optional[StrictStr], Field(description="Preferred output language for UI-facing fields (fallback when ?lang is not provided).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AIQueryResponse]:
        """Ai Query


        :param db_name: (required)
        :type db_name: str
        :param ai_query_request: (required)
        :type ai_query_request: AIQueryRequest
        :param dry_run: When true, return only the query plan without executing (same as translate/query-plan).
        :type dry_run: bool
        :param lang: Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.
        :type lang: str
        :param accept_language: Preferred output language for UI-facing fields (fallback when ?lang is not provided).
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._ai_query_api_v1_ai_query_db_name_post_serialize(
            db_name=db_name,
            ai_query_request=ai_query_request,
            dry_run=dry_run,
            lang=lang,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AIQueryResponse",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def ai_query_api_v1_ai_query_db_name_post_without_preload_content(
        self,
        db_name: StrictStr,
        ai_query_request: AIQueryRequest,
        dry_run: Annotated[Optional[StrictBool], Field(description="When true, return only the query plan without executing (same as translate/query-plan).")] = None,
        lang: Annotated[Optional[StrictStr], Field(description="Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.")] = None,
        accept_language: Annotated[Optional[StrictStr], Field(description="Preferred output language for UI-facing fields (fallback when ?lang is not provided).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Ai Query


        :param db_name: (required)
        :type db_name: str
        :param ai_query_request: (required)
        :type ai_query_request: AIQueryRequest
        :param dry_run: When true, return only the query plan without executing (same as translate/query-plan).
        :type dry_run: bool
        :param lang: Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.
        :type lang: str
        :param accept_language: Preferred output language for UI-facing fields (fallback when ?lang is not provided).
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._ai_query_api_v1_ai_query_db_name_post_serialize(
            db_name=db_name,
            ai_query_request=ai_query_request,
            dry_run=dry_run,
            lang=lang,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AIQueryResponse",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _ai_query_api_v1_ai_query_db_name_post_serialize(
        self,
        db_name,
        ai_query_request,
        dry_run,
        lang,
        accept_language,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if db_name is not None:
            _path_params['db_name'] = db_name
        # process the query parameters
        if dry_run is not None:
            
            _query_params.append(('dry_run', dry_run))
            
        if lang is not None:
            
            _query_params.append(('lang', lang))
            
        # process the header parameters
        if accept_language is not None:
            _header_params['Accept-Language'] = accept_language
        # process the form parameters
        # process the body parameter
        if ai_query_request is not None:
            _body_params = ai_query_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/ai/query/{db_name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def translate_query_plan_api_v1_ai_translate_query_plan_db_name_post(
        self,
        db_name: StrictStr,
        ai_query_request: AIQueryRequest,
        lang: Annotated[Optional[StrictStr], Field(description="Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.")] = None,
        accept_language: Annotated[Optional[StrictStr], Field(description="Preferred output language for UI-facing fields (fallback when ?lang is not provided).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """(Deprecated) Translate Query Plan

        Deprecated: use ``POST /ai/query/{db_name}?dry_run=true`` instead.

        :param db_name: (required)
        :type db_name: str
        :param ai_query_request: (required)
        :type ai_query_request: AIQueryRequest
        :param lang: Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.
        :type lang: str
        :param accept_language: Preferred output language for UI-facing fields (fallback when ?lang is not provided).
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501
        warnings.warn("POST /api/v1/ai/translate/query-plan/{db_name} is deprecated.", DeprecationWarning)

        _param = self._translate_query_plan_api_v1_ai_translate_query_plan_db_name_post_serialize(
            db_name=db_name,
            ai_query_request=ai_query_request,
            lang=lang,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def translate_query_plan_api_v1_ai_translate_query_plan_db_name_post_with_http_info(
        self,
        db_name: StrictStr,
        ai_query_request: AIQueryRequest,
        lang: Annotated[Optional[StrictStr], Field(description="Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.")] = None,
        accept_language: Annotated[Optional[StrictStr], Field(description="Preferred output language for UI-facing fields (fallback when ?lang is not provided).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """(Deprecated) Translate Query Plan

        Deprecated: use ``POST /ai/query/{db_name}?dry_run=true`` instead.

        :param db_name: (required)
        :type db_name: str
        :param ai_query_request: (required)
        :type ai_query_request: AIQueryRequest
        :param lang: Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.
        :type lang: str
        :param accept_language: Preferred output language for UI-facing fields (fallback when ?lang is not provided).
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501
        warnings.warn("POST /api/v1/ai/translate/query-plan/{db_name} is deprecated.", DeprecationWarning)

        _param = self._translate_query_plan_api_v1_ai_translate_query_plan_db_name_post_serialize(
            db_name=db_name,
            ai_query_request=ai_query_request,
            lang=lang,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def translate_query_plan_api_v1_ai_translate_query_plan_db_name_post_without_preload_content(
        self,
        db_name: StrictStr,
        ai_query_request: AIQueryRequest,
        lang: Annotated[Optional[StrictStr], Field(description="Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.")] = None,
        accept_language: Annotated[Optional[StrictStr], Field(description="Preferred output language for UI-facing fields (fallback when ?lang is not provided).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """(Deprecated) Translate Query Plan

        Deprecated: use ``POST /ai/query/{db_name}?dry_run=true`` instead.

        :param db_name: (required)
        :type db_name: str
        :param ai_query_request: (required)
        :type ai_query_request: AIQueryRequest
        :param lang: Output language override for UI-facing fields (EN/KR). Overrides Accept-Language.
        :type lang: str
        :param accept_language: Preferred output language for UI-facing fields (fallback when ?lang is not provided).
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501
        warnings.warn("POST /api/v1/ai/translate/query-plan/{db_name} is deprecated.", DeprecationWarning)

        _param = self._translate_query_plan_api_v1_ai_translate_query_plan_db_name_post_serialize(
            db_name=db_name,
            ai_query_request=ai_query_request,
            lang=lang,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _translate_query_plan_api_v1_ai_translate_query_plan_db_name_post_serialize(
        self,
        db_name,
        ai_query_request,
        lang,
        accept_language,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if db_name is not None:
            _path_params['db_name'] = db_name
        # process the query parameters
        if lang is not None:
            
            _query_params.append(('lang', lang))
            
        # process the header parameters
        if accept_language is not None:
            _header_params['Accept-Language'] = accept_language
        # process the form parameters
        # process the body parameter
        if ai_query_request is not None:
            _body_params = ai_query_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/ai/translate/query-plan/{db_name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


