from enum import Enum


class ErrorCategory(str, Enum):
    INPUT = "input"
    AUTH = "auth"
    PERMISSION = "permission"
    RESOURCE = "resource"
    CONFLICT = "conflict"
    RATE_LIMIT = "rate_limit"
    UPSTREAM = "upstream"
    INTERNAL = "internal"


class ErrorCode(str, Enum):
    REQUEST_VALIDATION_FAILED = "REQUEST_VALIDATION_FAILED"
    INPUT_SANITIZATION_FAILED = "INPUT_SANITIZATION_FAILED"
    JSON_DECODE_ERROR = "JSON_DECODE_ERROR"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID = "AUTH_INVALID"
    AUTH_EXPIRED = "AUTH_EXPIRED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    CONFLICT = "CONFLICT"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    RATE_LIMITED = "RATE_LIMITED"
    UPSTREAM_ERROR = "UPSTREAM_ERROR"
    UPSTREAM_TIMEOUT = "UPSTREAM_TIMEOUT"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
    DB_ERROR = "DB_ERROR"
    DB_UNAVAILABLE = "DB_UNAVAILABLE"
    DB_TIMEOUT = "DB_TIMEOUT"
    DB_CONSTRAINT_VIOLATION = "DB_CONSTRAINT_VIOLATION"
    TERMINUS_CONFLICT = "TERMINUS_CONFLICT"
    TERMINUS_UNAVAILABLE = "TERMINUS_UNAVAILABLE"
    OMS_UNAVAILABLE = "OMS_UNAVAILABLE"
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
