"""Typed legacy/external error codes used in detailed payloads.

These codes are resolved via ``_LEGACY_CODE_SPECS`` in enterprise_catalog and
travel alongside canonical ``ErrorCode`` values for better diagnostics.
"""

from enum import Enum


class LegacyErrorCode(str, Enum):
    SHEET_NOT_ACCESSIBLE = "SHEET_NOT_ACCESSIBLE"
    REPLAY_REQUIRED = "REPLAY_REQUIRED"
    DEFINITION_MISMATCH = "DEFINITION_MISMATCH"
    FUNNEL_UNAVAILABLE = "FUNNEL_UNAVAILABLE"
    SOURCE_FIELD_UNKNOWN = "SOURCE_FIELD_UNKNOWN"
    TARGET_FIELD_UNKNOWN = "TARGET_FIELD_UNKNOWN"
    RES001 = "RES001"
    RES002 = "RES002"

    MAPPING_SPEC_BACKING_SCHEMA_MISMATCH = "MAPPING_SPEC_BACKING_SCHEMA_MISMATCH"
    MAPPING_SPEC_SOURCE_MISSING = "MAPPING_SPEC_SOURCE_MISSING"
    MAPPING_SPEC_TARGET_UNKNOWN = "MAPPING_SPEC_TARGET_UNKNOWN"
    MAPPING_SPEC_RELATIONSHIP_CARDINALITY_UNSUPPORTED = "MAPPING_SPEC_RELATIONSHIP_CARDINALITY_UNSUPPORTED"
    MAPPING_SPEC_RELATIONSHIP_REQUIRED = "MAPPING_SPEC_RELATIONSHIP_REQUIRED"
    MAPPING_SPEC_PRIMARY_KEY_MISMATCH = "MAPPING_SPEC_PRIMARY_KEY_MISMATCH"
    MAPPING_SPEC_DATASET_PK_MISSING = "MAPPING_SPEC_DATASET_PK_MISSING"
    MAPPING_SPEC_DATASET_PK_TARGET_MISMATCH = "MAPPING_SPEC_DATASET_PK_TARGET_MISMATCH"
    MAPPING_SPEC_REQUIRED_SOURCE_MISSING = "MAPPING_SPEC_REQUIRED_SOURCE_MISSING"
    MAPPING_SPEC_REQUIRED_MISSING = "MAPPING_SPEC_REQUIRED_MISSING"
    MAPPING_SPEC_TITLE_KEY_MISSING = "MAPPING_SPEC_TITLE_KEY_MISSING"
    MAPPING_SPEC_UNIQUE_KEY_MISSING = "MAPPING_SPEC_UNIQUE_KEY_MISSING"
    MAPPING_SPEC_PRIMARY_KEY_MISSING = "MAPPING_SPEC_PRIMARY_KEY_MISSING"
    MAPPING_SPEC_UNSUPPORTED_TYPES = "MAPPING_SPEC_UNSUPPORTED_TYPES"
    MAPPING_SPEC_SOURCE_TYPE_UNKNOWN = "MAPPING_SPEC_SOURCE_TYPE_UNKNOWN"
    MAPPING_SPEC_SOURCE_TYPE_UNSUPPORTED = "MAPPING_SPEC_SOURCE_TYPE_UNSUPPORTED"
    MAPPING_SPEC_TYPE_INCOMPATIBLE = "MAPPING_SPEC_TYPE_INCOMPATIBLE"
    MAPPING_SPEC_TARGET_TYPE_MISMATCH = "MAPPING_SPEC_TARGET_TYPE_MISMATCH"
    MAPPING_SPEC_DATASET_MISMATCH = "MAPPING_SPEC_DATASET_MISMATCH"

    OBJECT_TYPE_CONTRACT_MISSING = "OBJECT_TYPE_CONTRACT_MISSING"
    OBJECT_TYPE_INACTIVE = "OBJECT_TYPE_INACTIVE"
    OBJECT_TYPE_PRIMARY_KEY_MISSING = "OBJECT_TYPE_PRIMARY_KEY_MISSING"
    OBJECT_TYPE_TITLE_KEY_MISSING = "OBJECT_TYPE_TITLE_KEY_MISSING"
    OBJECT_TYPE_BACKING_MISMATCH = "OBJECT_TYPE_BACKING_MISMATCH"
    OBJECT_TYPE_BACKING_DATASET_MISMATCH = "OBJECT_TYPE_BACKING_DATASET_MISMATCH"
    OBJECT_TYPE_SCHEMA_HASH_MISMATCH = "OBJECT_TYPE_SCHEMA_HASH_MISMATCH"
    OBJECT_TYPE_KEY_FIELDS_MISSING = "OBJECT_TYPE_KEY_FIELDS_MISSING"
    OBJECT_TYPE_AUTO_MAPPING_EMPTY = "OBJECT_TYPE_AUTO_MAPPING_EMPTY"
    OBJECT_TYPE_MAPPING_SPEC_REQUIRED = "OBJECT_TYPE_MAPPING_SPEC_REQUIRED"
    OBJECT_TYPE_BACKING_VERSION_REQUIRED = "OBJECT_TYPE_BACKING_VERSION_REQUIRED"
    OBJECT_TYPE_BACKING_ARTIFACT_REQUIRED = "OBJECT_TYPE_BACKING_ARTIFACT_REQUIRED"
    OBJECT_TYPE_EDIT_RESET_REQUIRED = "OBJECT_TYPE_EDIT_RESET_REQUIRED"
    OBJECT_TYPE_MIGRATION_REQUIRED = "OBJECT_TYPE_MIGRATION_REQUIRED"

    RELATIONSHIP_FK_TYPE_MISMATCH = "RELATIONSHIP_FK_TYPE_MISMATCH"
    RELATIONSHIP_SOURCE_PK_TYPE_MISMATCH = "RELATIONSHIP_SOURCE_PK_TYPE_MISMATCH"
    RELATIONSHIP_JOIN_SOURCE_TYPE_MISMATCH = "RELATIONSHIP_JOIN_SOURCE_TYPE_MISMATCH"
    RELATIONSHIP_JOIN_TARGET_TYPE_MISMATCH = "RELATIONSHIP_JOIN_TARGET_TYPE_MISMATCH"
