from __future__ import annotations

TABLE_IMPORT_MODE_ORDER = ("SNAPSHOT", "APPEND", "UPDATE", "INCREMENTAL", "CDC", "STREAMING")
TABLE_IMPORT_MODES = frozenset(TABLE_IMPORT_MODE_ORDER)
CDC_COMPAT_IMPORT_MODES = frozenset({"CDC", "STREAMING"})
APPEND_MERGE_IMPORT_MODES = frozenset({"APPEND", "INCREMENTAL", "CDC", "STREAMING"})
