#!/usr/bin/env python3
"""
Generate a repo-wide file inventory for documentation traceability.

Goal: every tracked code/config artifact in SPICE-Harvester should be discoverable
from the docs site (enterprise-grade "what exists where" view).

This generator uses `git ls-files` (when available) to avoid indexing local build
artifacts and untracked files. It falls back to a filesystem walk if git is not
available (e.g., exported source tarballs).
"""

from __future__ import annotations

import argparse
import os
import subprocess
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List, Optional


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "docs" / "reference" / "_generated" / "REPO_FILE_INVENTORY.md"


CODE_EXTS = {
    ".py",
    ".pyi",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".java",
    ".scala",
    ".sql",
    ".sh",
}
CONFIG_EXTS = {
    ".yml",
    ".yaml",
    ".json",
    ".toml",
    ".ini",
    ".cfg",
}
DOC_EXTS = {".md", ".rst"}


def _run_git_lines(args: List[str]) -> Optional[List[str]]:
    try:
        out = subprocess.check_output(args, cwd=str(REPO_ROOT), text=True, stderr=subprocess.DEVNULL)
    except Exception:
        return None
    return [line.strip() for line in out.splitlines() if line.strip()]


def _iter_files_fallback() -> Iterable[str]:
    # A conservative fallback: walk the repo but skip common build output dirs.
    skip_parts = {
        ".git",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        "node_modules",
        ".venv",
        ".venv-docs",
        ".venv-docs-py311",
        "docs/_build",
    }

    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        if any(part in skip_parts for part in path.parts):
            continue
        yield rel


def _iter_repo_files() -> List[str]:
    tracked = _run_git_lines(["git", "-c", "core.quotePath=false", "ls-files"])
    if tracked is not None:
        return tracked
    return list(_iter_files_fallback())


def _classify(path: str) -> str:
    p = Path(path)
    name = p.name
    suffix = p.suffix.lower()

    if name.startswith("Dockerfile") or name == "Makefile":
        return "infra"
    if suffix in CODE_EXTS:
        return "code"
    if suffix in CONFIG_EXTS:
        return "config"
    if suffix in DOC_EXTS:
        return "docs"
    return "other"


@dataclass(frozen=True)
class RepoStats:
    total: int
    by_top: Counter[str]
    by_kind: Counter[str]
    by_ext: Counter[str]


def _compute_stats(files: List[str]) -> RepoStats:
    by_top: Counter[str] = Counter()
    by_kind: Counter[str] = Counter()
    by_ext: Counter[str] = Counter()

    for f in files:
        parts = f.split("/", 1)
        top = parts[0] if len(parts) > 1 else "."
        by_top[top] += 1

        kind = _classify(f)
        by_kind[kind] += 1

        ext = Path(f).suffix.lower() or "(no_ext)"
        by_ext[ext] += 1

    return RepoStats(total=len(files), by_top=by_top, by_kind=by_kind, by_ext=by_ext)


def _render(files: List[str], repo_url: Optional[str], rev: Optional[str], generated_at: str) -> str:
    stats = _compute_stats(files)

    lines: List[str] = []
    lines.append("# Repo File Inventory (Auto-Generated)")
    lines.append("")
    lines.append("> This page is auto-generated by `scripts/generate_repo_file_inventory.py`.")
    lines.append(f"> Generated at: `{generated_at}`")
    if repo_url and rev:
        lines.append(f"> Source: `{repo_url}` @ `{rev}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total tracked files: **{stats.total}**")
    lines.append(
        "- By kind: "
        + ", ".join(f"`{k}`={v}" for k, v in sorted(stats.by_kind.items(), key=lambda kv: (-kv[1], kv[0])))
    )
    lines.append("")
    lines.append("### Top-Level Directories")
    lines.append("")
    lines.append("| Top | Files |")
    lines.append("| --- | ---: |")
    for top, count in sorted(stats.by_top.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| `{top}` | {count} |")
    lines.append("")
    lines.append("### File Extensions (Top 30)")
    lines.append("")
    lines.append("| Ext | Files |")
    lines.append("| --- | ---: |")
    for ext, count in sorted(stats.by_ext.items(), key=lambda kv: (-kv[1], kv[0]))[:30]:
        lines.append(f"| `{ext}` | {count} |")
    lines.append("")
    lines.append("## Inventory")
    lines.append("")
    lines.append(
        "Python source is additionally indexed in Sphinx AutoAPI at `docs/reference/autoapi/` during `sphinx-build`."
    )
    lines.append("")

    by_top_dir: dict[str, list[str]] = defaultdict(list)
    for f in files:
        parts = f.split("/", 1)
        top = parts[0] if len(parts) > 1 else "."
        by_top_dir[top].append(f)

    def _link(path: str) -> str:
        if repo_url and rev:
            return f"[`{path}`]({repo_url}/blob/{rev}/{path})"
        return f"`{path}`"

    for top in sorted(by_top_dir.keys()):
        lines.append(f"### `{top}`")
        lines.append("")
        for f in sorted(by_top_dir[top]):
            lines.append(f"- {_link(f)}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help="Path to generated markdown (default: docs/reference/_generated/REPO_FILE_INVENTORY.md)",
    )
    parser.add_argument(
        "--repo-url",
        type=str,
        default=None,
        help="Repository base URL (e.g., https://github.com/org/repo). Default: auto-detect from git.",
    )
    parser.add_argument(
        "--rev",
        type=str,
        default=None,
        help="Git revision to link to (sha/branch). Default: auto-detect HEAD.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the output would change",
    )
    return parser.parse_args()


def _detect_repo_url() -> Optional[str]:
    env_url = (os.environ.get("SPICE_DOCS_REPO_URL") or "").strip()
    if env_url:
        return env_url
    lines = _run_git_lines(["git", "config", "--get", "remote.origin.url"])
    if not lines:
        return None
    url = lines[0]
    if url.startswith("git@") and ":" in url:
        host, path = url.split(":", 1)
        host = host.replace("git@", "")
        url = f"https://{host}/{path}"
    if url.startswith("ssh://git@"):
        url = url.replace("ssh://git@", "https://", 1)
    if url.endswith(".git"):
        url = url[: -len(".git")]
    return url


def _detect_rev() -> Optional[str]:
    env_rev = (os.environ.get("SPICE_DOCS_GIT_REF") or "").strip()
    if env_rev:
        return env_rev
    lines = _run_git_lines(["git", "rev-parse", "HEAD"])
    return lines[0] if lines else None


def _detect_commit_time(rev: Optional[str]) -> str:
    """
    Prefer a deterministic timestamp derived from git history so the generated file
    is stable for a given commit (important for `--check` and clean diffs).
    """
    if not rev:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    lines = _run_git_lines(["git", "show", "-s", "--format=%cI", rev])
    return lines[0] if lines else datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")


def main() -> int:
    args = parse_args()
    output_path: Path = args.output

    files = _iter_repo_files()
    repo_url = args.repo_url or _detect_repo_url()
    rev = args.rev or _detect_rev()
    rendered = _render(files, repo_url, rev, generated_at=_detect_commit_time(rev))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    existing = output_path.read_text(encoding="utf-8") if output_path.exists() else None

    if args.check:
        if existing != rendered:
            print(f"{output_path} is out of date. Run: python scripts/generate_repo_file_inventory.py")
            return 1
        return 0

    output_path.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
